[View in Colaboratory](https://colab.research.google.com/github/desirajusantosh/DS/blob/master/random_forests_1.ipynb)

Random Forests

In [6]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [0]:
autoreload 2

In [0]:
%matplotlib inline

In [9]:
!pip install fastai
from fastai.imports import *

Requirement already satisfied: fastai in /usr/local/lib/python3.6/dist-packages (0.7.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from fastai) (2018.8.24)
Requirement already satisfied: traitlets in /usr/local/lib/python3.6/dist-packages (from fastai) (4.3.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from fastai) (0.1.7)
Requirement already satisfied: bcolz in /usr/local/lib/python3.6/dist-packages (from fastai) (1.2.1)
Requirement already satisfied: jedi in /usr/local/lib/python3.6/dist-packages (from fastai) (0.12.1)
Requirement already satisfied: Pygments in /usr/local/lib/python3.6/dist-packages (from fastai) (2.1.3)
Requirement already satisfied: plotnine in /usr/local/lib/python3.6/dist-packages (from fastai) (0.4.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from fastai) (0.9)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages (from fastai) (3.4.3.18)
Requirement already satisfied: Pillow in /usr/local/lib/python3.6/dist-packages (from fastai) (4.0.0)
Requirement already satisfied: pyzmq in /usr/local/lib/python3.6/dist-packages (from fastai) (16.0.4)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.6/dist-packages (from fastai) (0.2.3)
Requirement already satisfied: torchvision in /usr/local/lib/python3.6/dist-packages (from fastai) (0.2.1)
Requirement already satisfied: pandas-summary in /usr/local/lib/python3.6/dist-packages (from fastai) (0.0.5)
Requirement already satisfied: feather-format in /usr/local/lib/python3.6/dist-packages (from fastai) (0.4.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from fastai) (2.1.2)
Requirement already satisfied: seaborn in /usr/local/lib/python3.6/dist-packages (from fastai) (0.7.1)
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.6/dist-packages (from fastai) (2.10)
Requirement already satisfied: torch<0.4 in /usr/local/lib/python3.6/dist-packages (from fastai) (0.3.1)
Requirement already satisfied: sklearn-pandas in /usr/local/lib/python3.6/dist-packages (from fastai) (1.7.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.6/dist-packages (from fastai) (5.5.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from fastai) (4.3.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/dist-packages (from fastai) (3.13)
Requirement already satisfied: testpath in /usr/local/lib/python3.6/dist-packages (from fastai) (0.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from fastai) (0.22.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.6/dist-packages (from fastai) (2.1.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from fastai) (2.5.3)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python3.6/dist-packages (from fastai) (1.0)
Requirement already satisfied: jupyter in /usr/local/lib/python3.6/dist-packages (from fastai) (1.0.0)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.6/dist-packages (from fastai) (2.2.1)
Requirement already satisfied: simplegeneric in /usr/local/lib/python3.6/dist-packages (from fastai) (0.8.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from fastai) (0.19.1)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.6/dist-packages (from fastai) (4.6.1)
Requirement already satisfied: cycler in /usr/local/lib/python3.6/dist-packages (from fastai) (0.10.0)
Requirement already satisfied: html5lib in /usr/local/lib/python3.6/dist-packages (from fastai) (1.0.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from fastai) (4.26.0)
Requirement already satisfied: isoweek in /usr/local/lib/python3.6/dist-packages (from fastai) (1.3.3)
Requirement already satisfied: widgetsnbextension in /usr/local/lib/python3.6/dist-packages (from fastai) (3.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from fastai) (0.7.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from fastai) (1.14.6)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from fastai) (0.2.0)
Requirement already satisfied: torchtext in /usr/local/lib/python3.6/dist-packages (from fastai) (0.2.3)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.6/dist-packages (from fastai) (0.6.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/dist-packages (from fastai) (2018.5)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.6/dist-packages (from fastai) (7.4.2)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.6/dist-packages (from fastai) (2.6.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/dist-packages (from fastai) (0.5.1)
Requirement already satisfied: tornado in /usr/local/lib/python3.6/dist-packages (from fastai) (4.5.3)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from traitlets->fastai) (1.11.0)
Requirement already satisfied: parso>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from jedi->fastai) (0.3.1)
Requirement already satisfied: patsy>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai) (0.5.0)
Requirement already satisfied: mizani>=0.4.5 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai) (0.4.6)
Requirement already satisfied: geopandas>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai) (0.4.0)
Requirement already satisfied: descartes>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai) (1.1.0)
Requirement already satisfied: statsmodels>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai) (0.8.0)
Requirement already satisfied: olefile in /usr/local/lib/python3.6/dist-packages (from Pillow->fastai) (0.46)
Requirement already satisfied: pyarrow>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from feather-format->fastai) (0.10.0)
Requirement already satisfied: scikit-learn>=0.15.0 in /usr/local/lib/python3.6/dist-packages (from sklearn-pandas->fastai) (0.19.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/dist-packages (from ipython->fastai) (39.1.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from ipython->fastai) (4.6.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from ipython->fastai) (1.0.15)
Requirement already satisfied: notebook in /usr/local/lib/python3.6/dist-packages (from jupyter->fastai) (5.2.2)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.6/dist-packages (from jupyter->fastai) (5.4.0)
Requirement already satisfied: qtconsole in /usr/local/lib/python3.6/dist-packages (from jupyter->fastai) (4.4.1)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.6/dist-packages (from jupyter->fastai) (5.2.0)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.6/dist-packages (from ipykernel->fastai) (5.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from torchtext->fastai) (2.18.4)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.6/dist-packages (from ipywidgets->fastai) (4.4.0)
Requirement already satisfied: palettable in /usr/local/lib/python3.6/dist-packages (from mizani>=0.4.5->plotnine->fastai) (3.1.1)
Requirement already satisfied: shapely in /usr/local/lib/python3.6/dist-packages (from geopandas>=0.3.0->plotnine->fastai) (1.6.4.post2)
Requirement already satisfied: fiona in /usr/local/lib/python3.6/dist-packages (from geopandas>=0.3.0->plotnine->fastai) (1.7.13)
Requirement already satisfied: pyproj in /usr/local/lib/python3.6/dist-packages (from geopandas>=0.3.0->plotnine->fastai) (1.9.5.1)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.6/dist-packages (from notebook->jupyter->fastai) (4.4.0)
Requirement already satisfied: terminado>=0.3.3; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from notebook->jupyter->fastai) (0.8.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->jupyter->fastai) (1.4.2)
Requirement already satisfied: mistune>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->jupyter->fastai) (0.8.3)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.6/dist-packages (from nbconvert->jupyter->fastai) (0.5.0)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->torchtext->fastai) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->torchtext->fastai) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->torchtext->fastai) (3.0.4)
Requirement already satisfied: munch in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas>=0.3.0->plotnine->fastai) (2.3.2)
Requirement already satisfied: click-plugins in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas>=0.3.0->plotnine->fastai) (1.0.4)
Requirement already satisfied: cligj>=0.4 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas>=0.3.0->plotnine->fastai) (0.5.0)
Requirement already satisfied: click>=3.0 in /usr/local/lib/python3.6/dist-packages (from click-plugins->fiona->geopandas>=0.3.0->plotnine->fastai) (7.0)

In [0]:
from fastai.imports import *

In [0]:
from fastai.structured import *

In [0]:
from pandas_summary import DataFrameSummary

In [0]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [0]:
from IPython.display import display

In [0]:
from sklearn import metrics

In [16]:
!kaggle competitions download -c bluebook-for-bulldozers

/bin/bash: kaggle: command not found

In [17]:
!pip install git+https://github.com/floydwch/kaggle-cli.git

Collecting git+https://github.com/floydwch/kaggle-cli.git
  Cloning https://github.com/floydwch/kaggle-cli.git to /tmp/pip-req-build-cby0nnsu
Collecting cliff<2.9,>=2.8.0 (from kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/c2/ba/f45621f885ecd8527142811c279740367eb6c552ceb8debfdb7c5fca0677/cliff-2.8.2.tar.gz (72kB)
    100% |████████████████████████████████| 81kB 3.2MB/s
Collecting MechanicalSoup<0.9,>=0.7.0 (from kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/5c/2e/f63ed26b51e36efa4cc22cad18187fcb0a253f756d548c96bb931f13de98/MechanicalSoup-0.8.0-py2.py3-none-any.whl
Collecting lxml<4.1,>=4.0.0 (from kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/a0/b5/4c6995f8f259f0858f79460e6d277888f8498ce1c1a466dfbb24f06ba83f/lxml-4.0.0-cp36-cp36m-manylinux1_x86_64.whl (5.3MB)
    100% |████████████████████████████████| 5.3MB 4.7MB/s
Collecting cssselect<1.1,>=1.0.1 (from kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/7b/44/25b7283e50585f0b4156960691d951b05d061abf4a714078393e51929b30/cssselect-1.0.3-py2.py3-none-any.whl
Collecting configparser (from kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Collecting progressbar2<3.35,>=3.34.3 (from kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/87/31/b984e17bcc7491c1baeda3906fe3abc14cb5cd5dbd046ab46d9fc7a2edfd/progressbar2-3.34.3-py2.py3-none-any.whl
Requirement already satisfied: beautifulsoup4<4.7,>=4.6.0 in /usr/local/lib/python3.6/dist-packages (from kaggle-cli==0.13.0) (4.6.3)
Collecting pbr!=2.1.0,>=2.0.0 (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/69/1c/98cba002ed975a91a0294863d9c774cc0ebe38e05bbb65e83314550b1677/pbr-4.2.0-py2.py3-none-any.whl (100kB)
    100% |████████████████████████████████| 102kB 27.7MB/s
Collecting cmd2>=0.6.7 (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/4c/72/8d6638256ae3eea143d94239e98c94d68a8453a226a0cf25a0cc306a7dd5/cmd2-0.9.4-py3-none-any.whl (75kB)
    100% |████████████████████████████████| 81kB 20.8MB/s
Collecting PrettyTable<0.8,>=0.7.1 (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
Requirement already satisfied: pyparsing>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (2.2.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (1.11.0)
Collecting stevedore>=1.20.0 (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/a1/d9/93a975469c53a9ee85de9ec0deb12345aa777748b4c263860668592344fe/stevedore-1.29.0-py2.py3-none-any.whl
Requirement already satisfied: PyYAML>=3.10.0 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (3.13)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python3.6/dist-packages (from MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (2.18.4)
Collecting python-utils>=2.1.0 (from progressbar2<3.35,>=3.34.3->kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/eb/a0/19119d8b7c05be49baf6c593f11c432d571b70d805f2fe94c0585e55e4c8/python_utils-2.3.0-py2.py3-none-any.whl
Requirement already satisfied: wcwidth; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from cmd2>=0.6.7->cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (0.1.7)
Collecting colorama (from cmd2>=0.6.7->cliff<2.9,>=2.8.0->kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting attrs (from cmd2>=0.6.7->cliff<2.9,>=2.8.0->kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting pyperclip>=1.5.27 (from cmd2>=0.6.7->cliff<2.9,>=2.8.0->kaggle-cli==0.13.0)
  Downloading https://files.pythonhosted.org/packages/2d/0f/4eda562dffd085945d57c2d9a5da745cfb5228c02bc90f2c74bbac746243/pyperclip-1.7.0.tar.gz
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (2018.8.24)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (2.6)
Building wheels for collected packages: kaggle-cli, cliff, configparser, PrettyTable, pyperclip
  Running setup.py bdist_wheel for kaggle-cli ... - done
  Stored in directory: /tmp/pip-ephem-wheel-cache-so6_qpjl/wheels/c2/d0/54/64709fb6e7766205e35b5f27e0ecd63a7ae179cadd44d14845
  Running setup.py bdist_wheel for cliff ... - \ done
  Stored in directory: /root/.cache/pip/wheels/02/22/09/66f8c243f9c68dee7e6456a0fd6c117439a64394fdaf02d965
  Running setup.py bdist_wheel for configparser ... - done
  Stored in directory: /root/.cache/pip/wheels/a3/61/79/424ef897a2f3b14684a7de5d89e8600b460b89663e6ce9d17c
  Running setup.py bdist_wheel for PrettyTable ... - done
  Stored in directory: /root/.cache/pip/wheels/80/34/1c/3967380d9676d162cb59513bd9dc862d0584e045a162095606
  Running setup.py bdist_wheel for pyperclip ... - done
  Stored in directory: /root/.cache/pip/wheels/92/f0/ac/2ba2972034e98971c3654ece337ac61e546bdeb34ca960dc8c
Successfully built kaggle-cli cliff configparser PrettyTable pyperclip
Installing collected packages: pbr, colorama, attrs, pyperclip, cmd2, PrettyTable, stevedore, cliff, MechanicalSoup, lxml, cssselect, configparser, python-utils, progressbar2, kaggle-cli
Successfully installed MechanicalSoup-0.8.0 PrettyTable-0.7.2 attrs-18.2.0 cliff-2.8.2 cmd2-0.9.4 colorama-0.3.9 configparser-3.5.0 cssselect-1.0.3 kaggle-cli-0.13.0 lxml-4.0.0 pbr-4.2.0 progressbar2-3.34.3 pyperclip-1.7.0 python-utils-2.3.0 stevedore-1.29.0

In [18]:
!kaggle competitions download -c bluebook-for-bulldozers -u santosh7

/bin/bash: kaggle: command not found

In [19]:
!kaggle config -g -u ‘santosh7’ -p ‘Kaggle2015’ -c ‘bluebook-for-bulldozers’

/bin/bash: kaggle: command not found

In [20]:
!pip install kaggle

Collecting kaggle
  Downloading https://files.pythonhosted.org/packages/c6/78/832b9a9ec6b3baf8ec566e1f0a695f2fd08d2c94a6797257a106304bfc3c/kaggle-1.4.7.1.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 2.8MB/s
Requirement already satisfied: urllib3<1.23.0,>=1.15 in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.22)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from kaggle) (2018.8.24)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from kaggle) (2.5.3)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from kaggle) (2.18.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from kaggle) (4.26.0)
Collecting python-slugify (from kaggle)
  Downloading https://files.pythonhosted.org/packages/00/ad/c778a6df614b6217c30fe80045b365bfa08b5dd3cb02e8b37a6d25126781/python-slugify-1.2.6.tar.gz
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle) (3.0.4)
Collecting Unidecode>=0.04.16 (from python-slugify->kaggle)
  Downloading https://files.pythonhosted.org/packages/59/ef/67085e30e8bbcdd76e2f0a4ad8151c13a2c5bce77c85f8cad6e1f16fb141/Unidecode-1.0.22-py2.py3-none-any.whl (235kB)
    100% |████████████████████████████████| 235kB 5.4MB/s
Building wheels for collected packages: kaggle, python-slugify
  Running setup.py bdist_wheel for kaggle ... - \ done
  Stored in directory: /root/.cache/pip/wheels/44/2c/df/22a6eeb780c36c28190faef6252b739fdc47145fd87a6642d4
  Running setup.py bdist_wheel for python-slugify ... - done
  Stored in directory: /root/.cache/pip/wheels/e3/65/da/2045deea3098ed7471eca0e2460cfbd3fdfe8c1d6fa6fcac92
Successfully built kaggle python-slugify
Installing collected packages: Unidecode, python-slugify, kaggle
Successfully installed Unidecode-1.0.22 kaggle-1.4.7.1 python-slugify-1.2.6

In [21]:
!ls sample_data/

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md

In [22]:
!kaggle competitions download -c bluebook-for-bulldozers

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 7, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.6/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.6/dist-packages/kaggle/api/kaggle_api_extended.py", line 110, in authenticate
    self._load_config(config_data)
  File "/usr/local/lib/python3.6/dist-packages/kaggle/api/kaggle_api_extended.py", line 149, in _load_config
    raise ValueError('Error: Missing %s in configuration.' % item)
ValueError: Error: Missing username in configuration.

In [23]:
cp /root/.kaggle-cli/config /root/.kaggle/kaggle.json

cp: cannot stat '/root/.kaggle-cli/config': No such file or directory

In [24]:
!kaggle competitions download -c bluebook-for-bulldozers

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 7, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.6/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.6/dist-packages/kaggle/api/kaggle_api_extended.py", line 110, in authenticate
    self._load_config(config_data)
  File "/usr/local/lib/python3.6/dist-packages/kaggle/api/kaggle_api_extended.py", line 149, in _load_config
    raise ValueError('Error: Missing %s in configuration.' % item)
ValueError: Error: Missing username in configuration.

In [25]:
!head /root/.kaggle/kaggle.json

head: cannot open '/root/.kaggle/kaggle.json' for reading: No such file or directory

In [26]:
!kaggle datasets list

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 7, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.6/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.6/dist-packages/kaggle/api/kaggle_api_extended.py", line 110, in authenticate
    self._load_config(config_data)
  File "/usr/local/lib/python3.6/dist-packages/kaggle/api/kaggle_api_extended.py", line 149, in _load_config
    raise ValueError('Error: Missing %s in configuration.' % item)
ValueError: Error: Missing username in configuration.

In [27]:
!head /content/.kaggle/kaggle.json

head: cannot open '/content/.kaggle/kaggle.json' for reading: No such file or directory

In [0]:
import json

In [0]:
token = {"username":"santosh7","key":"422fdad87a7bb7199b50f3807d828147"}

In [0]:
!mkdir /content/.kaggle
!touch /content/.kaggle/kaggle.json
with open("/content/.kaggle/kaggle.json", "w") as file:
  json.dump(token,file)

In [0]:
!chmod 600 /content/.kaggle/kaggle.json
!cp /content/.kaggle/kaggle.json ~/.kaggle/kaggle.json

In [32]:
!kaggle competitions download -c bluebook-for-bulldozers

Downloading Train.7z to /content
 73% 5.00M/6.85M [00:00<00:00, 44.6MB/s]
100% 6.85M/6.85M [00:00<00:00, 57.3MB/s]
Downloading Train.zip to /content
 54% 5.00M/9.28M [00:00<00:00, 36.1MB/s]
100% 9.28M/9.28M [00:00<00:00, 60.4MB/s]
Downloading Valid.7z to /content
  0% 0.00/209k [00:00<?, ?B/s]
100% 209k/209k [00:00<00:00, 132MB/s]
Downloading Valid.csv to /content
  0% 0.00/3.17M [00:00<?, ?B/s]
100% 3.17M/3.17M [00:00<00:00, 242MB/s]
Downloading Valid.zip to /content
  0% 0.00/297k [00:00<?, ?B/s]
100% 297k/297k [00:00<00:00, 147MB/s]
Downloading Data%20Dictionary.xlsx to /content
  0% 0.00/10.8k [00:00<?, ?B/s]
100% 10.8k/10.8k [00:00<00:00, 11.2MB/s]
Downloading median_benchmark.csv to /content
  0% 0.00/192k [00:00<?, ?B/s]
100% 192k/192k [00:00<00:00, 100MB/s]
Downloading Machine_Appendix.csv to /content
 63% 31.0M/49.1M [00:00<00:00, 56.1MB/s]
100% 49.1M/49.1M [00:00<00:00, 174MB/s]
Downloading ValidSolution.csv to /content
  0% 0.00/316k [00:00<?, ?B/s]
100% 316k/316k [00:00<00:00, 110MB/s]
Downloading TrainAndValid.7z to /content
 85% 6.00M/7.06M [00:00<00:00, 60.9MB/s]
100% 7.06M/7.06M [00:00<00:00, 68.8MB/s]
Downloading TrainAndValid.csv to /content
 91% 104M/114M [00:00<00:00, 133MB/s]
100% 114M/114M [00:00<00:00, 179MB/s]
Downloading TrainAndValid.zip to /content
 52% 5.00M/9.59M [00:00<00:00, 46.3MB/s]
100% 9.59M/9.59M [00:00<00:00, 76.0MB/s]
Downloading Test.csv to /content
  0% 0.00/3.40M [00:00<?, ?B/s]
100% 3.40M/3.40M [00:00<00:00, 262MB/s]
Downloading random_forest_benchmark_test.csv to /content
  0% 0.00/207k [00:00<?, ?B/s]
100% 207k/207k [00:00<00:00, 107MB/s]

In [33]:
!ls

Data%20Dictionary.xlsx		  Test.csv	     Train.zip
Machine_Appendix.csv		  Train.7z	     Valid.7z
median_benchmark.csv		  TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data			  TrainAndValid.zip  Valid.zip

In [34]:
!pwd

/content

In [0]:
PATH = "~/content/"

In [0]:
!gzip Train.zip

In [37]:
ls

Data%20Dictionary.xlsx            Test.csv           Train.zip.gz
Machine_Appendix.csv              Train.7z           Valid.7z
median_benchmark.csv              TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data/                      TrainAndValid.zip  Valid.zip

In [0]:
!gunzip Train.zip.gz

In [39]:
!ls

Data%20Dictionary.xlsx		  Test.csv	     Train.zip
Machine_Appendix.csv		  Train.7z	     Valid.7z
median_benchmark.csv		  TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data			  TrainAndValid.zip  Valid.zip

In [40]:
!unzip Train.zip

Archive:  Train.zip
  inflating: Train.csv

In [41]:
!ls -ltr

total 322504
-rw-r--r-- 1 root root 116403970 Jan 24  2013 Train.csv
drwxr-xr-x 2 root root      4096 Sep 27 20:32 sample_data
-rw-r--r-- 1 root root   7183499 Sep 28 21:53 Train.7z
-rw-r--r-- 1 root root   9732240 Sep 28 21:53 Train.zip
-rw-r--r-- 1 root root    214480 Sep 28 21:53 Valid.7z
-rw-r--r-- 1 root root   3318969 Sep 28 21:53 Valid.csv
-rw-r--r-- 1 root root    303660 Sep 28 21:53 Valid.zip
-rw-r--r-- 1 root root     11063 Sep 28 21:53 Data%20Dictionary.xlsx
-rw-r--r-- 1 root root    196760 Sep 28 21:53 median_benchmark.csv
-rw-r--r-- 1 root root  51498702 Sep 28 21:53 Machine_Appendix.csv
-rw-r--r-- 1 root root    323524 Sep 28 21:53 ValidSolution.csv
-rw-r--r-- 1 root root   7403772 Sep 28 21:53 TrainAndValid.7z
-rw-r--r-- 1 root root 119791159 Sep 28 21:53 TrainAndValid.csv
-rw-r--r-- 1 root root  10057248 Sep 28 21:53 TrainAndValid.zip
-rw-r--r-- 1 root root   3560907 Sep 28 21:53 Test.csv
-rw-r--r-- 1 root root    211941 Sep 28 21:53 random_forest_benchmark_test.csv

In [42]:
PATH = "/content/"
!ls {PATH}

Data%20Dictionary.xlsx		  Train.7z	     Valid.7z
Machine_Appendix.csv		  TrainAndValid.7z   Valid.csv
median_benchmark.csv		  TrainAndValid.csv  ValidSolution.csv
random_forest_benchmark_test.csv  TrainAndValid.zip  Valid.zip
sample_data			  Train.csv
Test.csv			  Train.zip

In [43]:
ls

Data%20Dictionary.xlsx            Train.7z           Valid.7z
Machine_Appendix.csv              TrainAndValid.7z   Valid.csv
median_benchmark.csv              TrainAndValid.csv  ValidSolution.csv
random_forest_benchmark_test.csv  TrainAndValid.zip  Valid.zip
sample_data/                      Train.csv
Test.csv                          Train.zip

In [44]:
ls

Data%20Dictionary.xlsx            Train.7z           Valid.7z
Machine_Appendix.csv              TrainAndValid.7z   Valid.csv
median_benchmark.csv              TrainAndValid.csv  ValidSolution.csv
random_forest_benchmark_test.csv  TrainAndValid.zip  Valid.zip
sample_data/                      Train.csv
Test.csv                          Train.zip

In [45]:
pwd

'/content'

In [46]:
!head Train.csv

SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,ProductSize,fiProductClassDesc,state,ProductGroup,ProductGroupDesc,Drive_System,Enclosure,Forks,Pad_Type,Ride_Control,Stick,Transmission,Turbocharged,Blade_Extension,Blade_Width,Enclosure_Type,Engine_Horsepower,Hydraulics,Pushblock,Ripper,Scarifier,Tip_Control,Tire_Size,Coupler,Coupler_System,Grouser_Tracks,Hydraulics_Flow,Track_Type,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
1139246,66000,999089,3157,121,3,2004,68,Low,11/16/2006 0:00,521D,521,D,,,,Wheel Loader - 110.0 to 120.0 Horsepower,Alabama,WL,Wheel Loader,,EROPS w AC,None or Unspecified,,None or Unspecified,,,,,,,,2 Valve,,,,,None or Unspecified,None or Unspecified,,,,,,,,,,,,,Standard,Conventional
1139248,57000,117657,77,121,3,1996,4640,Low,3/26/2004 0:00,950FII,950,F,II,,Medium,Wheel Loader - 150.0 to 175.0 Horsepower,North Carolina,WL,Wheel Loader,,EROPS w AC,None or Unspecified,,None or Unspecified,,,,,,,,2 Valve,,,,,23.5,None or Unspecified,,,,,,,,,,,,,Standard,Conventional
1139249,10000,434808,7009,121,3,2001,2838,High,2/26/2004 0:00,226,226,,,,,Skid Steer Loader - 1351.0 to 1601.0 Lb Operating Capacity,New York,SSL,Skid Steer Loaders,,OROPS,None or Unspecified,,,,,,,,,,Auxiliary,,,,,,None or Unspecified,None or Unspecified,None or Unspecified,Standard,,,,,,,,,,,
1139251,38500,1026470,332,121,3,2001,3486,High,5/19/2011 0:00,PC120-6E,PC120,,-6E,,Small,"Hydraulic Excavator, Track - 12.0 to 14.0 Metric Tons",Texas,TEX,Track Excavators,,EROPS w AC,,,,,,,,,,,2 Valve,,,,,,None or Unspecified,,,,,,,,,,,,,,
1139253,11000,1057373,17311,121,3,2007,722,Medium,7/23/2009 0:00,S175,S175,,,,,Skid Steer Loader - 1601.0 to 1751.0 Lb Operating Capacity,New York,SSL,Skid Steer Loaders,,EROPS,None or Unspecified,,,,,,,,,,Auxiliary,,,,,,None or Unspecified,None or Unspecified,None or Unspecified,Standard,,,,,,,,,,,
1139255,26500,1001274,4605,121,3,2004,508,Low,12/18/2008 0:00,310G,310,G,,,,Backhoe Loader - 14.0 to 15.0 Ft Standard Digging Depth,Arizona,BL,Backhoe Loaders,Four Wheel Drive,OROPS,None or Unspecified,None or Unspecified,No,Extended,Powershuttle,None or Unspecified,,,,,,,,,,,,,,,,,,,,,,,,,
1139256,21000,772701,1937,121,3,1993,11540,High,8/26/2004 0:00,790ELC,790,E,,LC,Large / Medium,"Hydraulic Excavator, Track - 21.0 to 24.0 Metric Tons",Florida,TEX,Track Excavators,,EROPS,,,,,,,,,,,Standard,,,,,,None or Unspecified,,,,Steel,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,,,,,
1139261,27000,902002,3539,121,3,2001,4883,High,11/17/2005 0:00,416D,416,D,,,,Backhoe Loader - 14.0 to 15.0 Ft Standard Digging Depth,Illinois,BL,Backhoe Loaders,Four Wheel Drive,OROPS,None or Unspecified,Reversible,No,Standard,Standard,Yes,,,,,,,,,,,,,,,,,,,,,,,,,
1139272,21500,1036251,36003,121,3,2008,302,Low,8/27/2009 0:00,430HAG,430,HAG,,,Mini,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric Tons",Texas,TEX,Track Excavators,,EROPS,,,,,,,,,,,Auxiliary,,,,,,Manual,,,,Rubber,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,,,,,

In [47]:
name = 'Santosh'
f'Hello {name}'

'Hello Santosh'

In [0]:
df_raw= pd.read_csv(f'{PATH}Train.csv', low_memory=False, parse_dates=["saledate"])

In [49]:
df_raw

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,2004-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,2004-02-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,2011-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,2009-07-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1139255,26500,1001274,4605,121,3.0,2004,508.0,Low,2008-12-18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1139256,21000,772701,1937,121,3.0,1993,11540.0,High,2004-08-26,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
7,1139261,27000,902002,3539,121,3.0,2001,4883.0,High,2005-11-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1139272,21500,1036251,36003,121,3.0,2008,302.0,Low,2009-08-27,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
9,1139275,65000,1016474,3883,121,3.0,1000,20700.0,Medium,2007-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
10,1139278,24000,1024998,4605,121,3.0,2004,1414.0,Medium,2008-08-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1139282,22500,319906,5255,121,3.0,1998,2764.0,Low,2006-08-24,...,NaN,NaN,NaN,NaN,NaN,None or Unspecified,PAT,None or Unspecified,NaN,NaN
12,1139283,36000,1052214,2232,121,3.0,1998,0.0,NaN,2005-10-20,...,None or Unspecified,"11' 0""",None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
13,1139284,30500,1068082,3542,121,3.0,2001,1921.0,Medium,2006-01-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1139290,28000,1058450,5162,121,3.0,2004,320.0,Low,2006-01-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1139291,19000,1004810,4604,121,3.0,1999,2450.0,Medium,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1139292,13500,1026973,9510,121,3.0,1999,1972.0,Low,2007-06-14,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
17,1139299,9500,1002713,21442,121,3.0,2003,0.0,NaN,2010-01-28,...,16 inch,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
18,1139301,12500,125790,7040,121,3.0,2001,994.0,Low,2006-03-09,...,None or Unspecified,None or Unspecified,None or Unspecified,Yes,Double,NaN,NaN,NaN,NaN,NaN
19,1139304,11500,1011914,3177,121,3.0,1991,8005.0,Medium,2005-11-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1139311,41000,1014135,8867,121,3.0,2000,3259.0,Medium,2006-05-18,...,32 inch,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
21,1139333,34500,999192,3350,121,3.0,1000,16328.0,Medium,2006-10-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1139344,26000,1044500,7040,121,3.0,2005,109.0,Low,2007-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
23,1139346,73000,821452,85,121,3.0,1996,17033.0,High,2006-10-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
24,1139348,33000,294562,3542,121,3.0,2001,1877.0,Medium,2004-05-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1139351,12500,833838,7009,121,3.0,2003,1028.0,Medium,2006-03-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1139354,15500,565440,7040,121,3.0,2003,356.0,Low,2006-03-09,...,None or Unspecified,None or Unspecified,None or Unspecified,Yes,Double,NaN,NaN,NaN,NaN,NaN
27,1139356,53000,1004127,25458,121,3.0,2000,0.0,NaN,2007-02-22,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
28,1139357,46000,44800,19167,121,3.0,2004,904.0,Low,2007-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1139358,89000,1018076,1333,121,3.0,1998,10466.0,Medium,2006-06-01,...,None or Unspecified,"15' 9""",None or Unspecified,Yes,Double,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401095,6333259,10500,1872639,21437,149,1.0,2003,NaN,NaN,2011-12-14,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401096,6333260,10000,1816341,21437,149,2.0,2004,NaN,NaN,2011-09-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401097,6333261,8500,1843949,21437,149,1.0,2005,NaN,NaN,2011-10-28,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401098,6333262,10500,1791341,21437,149,2.0,2004,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401099,6333263,11000,1833174,21437,149,1.0,2004,NaN,NaN,2011-12-14,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401100,6333264,10500,1791370,21437,149,2.0,2004,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401101,6333270,10000,1799208,21437,149,1.0,2004,NaN,NaN,2011-12-14,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401102,6333272,10500,1927142,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401103,6333273,12500,1789856,21437,149,2.0,2005,NaN,NaN,2011-09-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401104,6333275,10500,1924623,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401105,6333276,10000,1835350,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401106,6333278,10500,1944702,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401107,6333279,12500,1866563,21437,149,2.0,2005,NaN,NaN,2011-09-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401108,6333280,10500,1851633,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401109,6333281,10500,1798958,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401110,6333282,10500,1878866,21437,149,2.0,2005,NaN,NaN,2011-09-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401111,6333283,10000,1874235,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401112,6333284,10500,1887654,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401113,6333285,10500,1817165,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401114,6333287,12500,1918242,21437,149,2.0,2005,NaN,NaN,2011-11-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401115,6333290,10000,1843374,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401116,6333302,8500,1825337,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401117,6333307,10000,1821747,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401118,6333311,9500,1828862,21437,149,2.0,2006,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401119,6333335,8500,1798293,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN

In [0]:
def display_all(df):
  with pd.option_context("display.max_rows", 1000, "display.max_columns", 1000):
    display(df)

In [51]:
display_all(df_raw.tail().T)

,401120,401121,401122,401123,401124
SalesID,6333336,6333337,6333338,6333341,6333342
SalePrice,10500,11000,11500,9000,7750
MachineID,1840702,1830472,1887659,1903570,1926965
ModelID,21439,21439,21439,21435,21435
datasource,149,149,149,149,149
auctioneerID,1,1,1,2,2
YearMade,2005,2005,2005,2005,2005
MachineHoursCurrentMeter,NaN,NaN,NaN,NaN,NaN
UsageBand,NaN,NaN,NaN,NaN,NaN
saledate,2011-11-02 00:00:00,2011-11-02 00:00:00,2011-11-02 00:00:00,2011-10-25 00:00:00,2011-10-25 00:00:00
fiModelDesc,35NX2,35NX2,35NX2,30NX,30NX
fiBaseModel,35,35,35,30,30
fiSecondaryDesc,NX,NX,NX,NX,NX
fiModelSeries,2,2,2,NaN,NaN
fiModelDescriptor,NaN,NaN,NaN,NaN,NaN
ProductSize,Mini,Mini,Mini,Mini,Mini
fiProductClassDesc,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 2.0 to 3.0 Metric...","Hydraulic Excavator, Track - 2.0 to 3.0 Metric..."
state,Maryland,Maryland,Maryland,Florida,Florida
ProductGroup,TEX,TEX,TEX,TEX,TEX
ProductGroupDesc,Track Excavators,Track Excavators,Track Excavators,Track Excavators,Track Excavators
Drive_System,NaN,NaN,NaN,NaN,NaN
Enclosure,EROPS,EROPS,EROPS,EROPS,EROPS
Forks,NaN,NaN,NaN,NaN,NaN
Pad_Type,NaN,NaN,NaN,NaN,NaN
Ride_Control,NaN,NaN,NaN,NaN,NaN
Stick,NaN,NaN,NaN,NaN,NaN
Transmission,NaN,NaN,NaN,NaN,NaN
Turbocharged,NaN,NaN,NaN,NaN,NaN
Blade_Extension,NaN,NaN,NaN,NaN,NaN
Blade_Width,NaN,NaN,NaN,NaN,NaN
Enclosure_Type,NaN,NaN,NaN,NaN,NaN
Engine_Horsepower,NaN,NaN,NaN,NaN,NaN
Hydraulics,Auxiliary,Standard,Auxiliary,Standard,Standard
Pushblock,NaN,NaN,NaN,NaN,NaN
Ripper,NaN,NaN,NaN,NaN,NaN
Scarifier,NaN,NaN,NaN,NaN,NaN
Tip_Control,NaN,NaN,NaN,NaN,NaN
Tire_Size,NaN,NaN,NaN,NaN,NaN
Coupler,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Coupler_System,NaN,NaN,NaN,NaN,NaN
Grouser_Tracks,NaN,NaN,NaN,NaN,NaN
Hydraulics_Flow,NaN,NaN,NaN,NaN,NaN
Track_Type,Steel,Steel,Steel,Steel,Steel
Undercarriage_Pad_Width,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Stick_Length,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Thumb,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Pattern_Changer,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Grouser_Type,Double,Double,Double,Double,Double
Backhoe_Mounting,NaN,NaN,NaN,NaN,NaN
Blade_Type,NaN,NaN,NaN,NaN,NaN
Travel_Controls,NaN,NaN,NaN,NaN,NaN
Differential_Type,NaN,NaN,NaN,NaN,NaN
Steering_Controls,NaN,NaN,NaN,NaN,NaN

In [54]:
display_all(df_raw.tail().transpose())

,401120,401121,401122,401123,401124
SalesID,6333336,6333337,6333338,6333341,6333342
SalePrice,10500,11000,11500,9000,7750
MachineID,1840702,1830472,1887659,1903570,1926965
ModelID,21439,21439,21439,21435,21435
datasource,149,149,149,149,149
auctioneerID,1,1,1,2,2
YearMade,2005,2005,2005,2005,2005
MachineHoursCurrentMeter,NaN,NaN,NaN,NaN,NaN
UsageBand,NaN,NaN,NaN,NaN,NaN
saledate,2011-11-02 00:00:00,2011-11-02 00:00:00,2011-11-02 00:00:00,2011-10-25 00:00:00,2011-10-25 00:00:00
fiModelDesc,35NX2,35NX2,35NX2,30NX,30NX
fiBaseModel,35,35,35,30,30
fiSecondaryDesc,NX,NX,NX,NX,NX
fiModelSeries,2,2,2,NaN,NaN
fiModelDescriptor,NaN,NaN,NaN,NaN,NaN
ProductSize,Mini,Mini,Mini,Mini,Mini
fiProductClassDesc,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 2.0 to 3.0 Metric...","Hydraulic Excavator, Track - 2.0 to 3.0 Metric..."
state,Maryland,Maryland,Maryland,Florida,Florida
ProductGroup,TEX,TEX,TEX,TEX,TEX
ProductGroupDesc,Track Excavators,Track Excavators,Track Excavators,Track Excavators,Track Excavators
Drive_System,NaN,NaN,NaN,NaN,NaN
Enclosure,EROPS,EROPS,EROPS,EROPS,EROPS
Forks,NaN,NaN,NaN,NaN,NaN
Pad_Type,NaN,NaN,NaN,NaN,NaN
Ride_Control,NaN,NaN,NaN,NaN,NaN
Stick,NaN,NaN,NaN,NaN,NaN
Transmission,NaN,NaN,NaN,NaN,NaN
Turbocharged,NaN,NaN,NaN,NaN,NaN
Blade_Extension,NaN,NaN,NaN,NaN,NaN
Blade_Width,NaN,NaN,NaN,NaN,NaN
Enclosure_Type,NaN,NaN,NaN,NaN,NaN
Engine_Horsepower,NaN,NaN,NaN,NaN,NaN
Hydraulics,Auxiliary,Standard,Auxiliary,Standard,Standard
Pushblock,NaN,NaN,NaN,NaN,NaN
Ripper,NaN,NaN,NaN,NaN,NaN
Scarifier,NaN,NaN,NaN,NaN,NaN
Tip_Control,NaN,NaN,NaN,NaN,NaN
Tire_Size,NaN,NaN,NaN,NaN,NaN
Coupler,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Coupler_System,NaN,NaN,NaN,NaN,NaN
Grouser_Tracks,NaN,NaN,NaN,NaN,NaN
Hydraulics_Flow,NaN,NaN,NaN,NaN,NaN
Track_Type,Steel,Steel,Steel,Steel,Steel
Undercarriage_Pad_Width,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Stick_Length,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Thumb,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Pattern_Changer,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Grouser_Type,Double,Double,Double,Double,Double
Backhoe_Mounting,NaN,NaN,NaN,NaN,NaN
Blade_Type,NaN,NaN,NaN,NaN,NaN
Travel_Controls,NaN,NaN,NaN,NaN,NaN
Differential_Type,NaN,NaN,NaN,NaN,NaN
Steering_Controls,NaN,NaN,NaN,NaN,NaN

In [0]:
df_raw.SalePrice = np.log(df_raw.SalePrice)

In [56]:
df_raw.SalePrice

0         11.097410
1         10.950807
2          9.210340
3         10.558414
4          9.305651
5         10.184900
6          9.952278
7         10.203592
8          9.975808
9         11.082143
10        10.085809
11        10.021271
12        10.491274
13        10.325482
14        10.239960
15         9.852194
16         9.510445
17         9.159047
18         9.433484
19         9.350102
20        10.621327
21        10.448715
22        10.165852
23        11.198215
24        10.404263
25         9.433484
26         9.648595
27        10.878047
28        10.736397
29        11.396392
            ...
401095     9.259131
401096     9.210340
401097     9.047821
401098     9.259131
401099     9.305651
401100     9.259131
401101     9.210340
401102     9.259131
401103     9.433484
401104     9.259131
401105     9.210340
401106     9.259131
401107     9.433484
401108     9.259131
401109     9.259131
401110     9.259131
401111     9.210340
401112     9.259131
401113     9.259131
401114     9.433484
401115     9.210340
401116     9.047821
401117     9.210340
401118     9.159047
401119     9.047821
401120     9.259131
401121     9.305651
401122     9.350102
401123     9.104980
401124     8.955448
Name: SalePrice, Length: 401125, dtype: float64

In [0]:
#Random Forest predict columns of any size.
## Generally does not overfit
##

In [68]:
train_cats(df_raw)
df_raw

m = RandomForestRegressor(n_jobs = -1)
m.fit(df_raw.drop('SalePrice',axis =1), df_raw.SalePrice)

ValueError: ignored

In [0]:
add_datepart(df_raw, 'saledate')

In [66]:
df_raw.saleYear.head()

0    2006
1    2004
2    2004
3    2011
4    2009
Name: saleYear, dtype: int64

In [70]:
df_raw
train_cats(df_raw)
df_raw

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,fiModelDesc,...,saleDay,saleDayofweek,saleDayofyear,saleIs_month_end,saleIs_month_start,saleIs_quarter_end,saleIs_quarter_start,saleIs_year_end,saleIs_year_start,saleElapsed
0,1139246,11.097410,999089,3157,121,3.0,2004,68.0,Low,521D,...,16,3,320,False,False,False,False,False,False,1163635200
1,1139248,10.950807,117657,77,121,3.0,1996,4640.0,Low,950FII,...,26,4,86,False,False,False,False,False,False,1080259200
2,1139249,9.210340,434808,7009,121,3.0,2001,2838.0,High,226,...,26,3,57,False,False,False,False,False,False,1077753600
3,1139251,10.558414,1026470,332,121,3.0,2001,3486.0,High,PC120-6E,...,19,3,139,False,False,False,False,False,False,1305763200
4,1139253,9.305651,1057373,17311,121,3.0,2007,722.0,Medium,S175,...,23,3,204,False,False,False,False,False,False,1248307200
5,1139255,10.184900,1001274,4605,121,3.0,2004,508.0,Low,310G,...,18,3,353,False,False,False,False,False,False,1229558400
6,1139256,9.952278,772701,1937,121,3.0,1993,11540.0,High,790ELC,...,26,3,239,False,False,False,False,False,False,1093478400
7,1139261,10.203592,902002,3539,121,3.0,2001,4883.0,High,416D,...,17,3,321,False,False,False,False,False,False,1132185600
8,1139272,9.975808,1036251,36003,121,3.0,2008,302.0,Low,430HAG,...,27,3,239,False,False,False,False,False,False,1251331200
9,1139275,11.082143,1016474,3883,121,3.0,1000,20700.0,Medium,988B,...,9,3,221,False,False,False,False,False,False,1186617600
10,1139278,10.085809,1024998,4605,121,3.0,2004,1414.0,Medium,310G,...,21,3,234,False,False,False,False,False,False,1219276800
11,1139282,10.021271,319906,5255,121,3.0,1998,2764.0,Low,D31E,...,24,3,236,False,False,False,False,False,False,1156377600
12,1139283,10.491274,1052214,2232,121,3.0,1998,0.0,NaN,PC200LC6,...,20,3,293,False,False,False,False,False,False,1129766400
13,1139284,10.325482,1068082,3542,121,3.0,2001,1921.0,Medium,420D,...,26,3,26,False,False,False,False,False,False,1138233600
14,1139290,10.239960,1058450,5162,121,3.0,2004,320.0,Low,214E,...,3,1,3,False,False,False,False,False,False,1136246400
15,1139291,9.852194,1004810,4604,121,3.0,1999,2450.0,Medium,310E,...,16,3,320,False,False,False,False,False,False,1163635200
16,1139292,9.510445,1026973,9510,121,3.0,1999,1972.0,Low,334,...,14,3,165,False,False,False,False,False,False,1181779200
17,1139299,9.159047,1002713,21442,121,3.0,2003,0.0,NaN,45NX,...,28,3,28,False,False,False,False,False,False,1264636800
18,1139301,9.433484,125790,7040,121,3.0,2001,994.0,Low,302.5,...,9,3,68,False,False,False,False,False,False,1141862400
19,1139304,9.350102,1011914,3177,121,3.0,1991,8005.0,Medium,580SUPER K,...,17,3,321,False,False,False,False,False,False,1132185600
20,1139311,10.621327,1014135,8867,121,3.0,2000,3259.0,Medium,JS260,...,18,3,138,False,False,False,False,False,False,1147910400
21,1139333,10.448715,999192,3350,121,3.0,1000,16328.0,Medium,120G,...,19,3,292,False,False,False,False,False,False,1161216000
22,1139344,10.165852,1044500,7040,121,3.0,2005,109.0,Low,302.5,...,25,3,298,False,False,False,False,False,False,1193270400
23,1139346,11.198215,821452,85,121,3.0,1996,17033.0,High,966FII,...,19,3,292,False,False,False,False,False,False,1161216000
24,1139348,10.404263,294562,3542,121,3.0,2001,1877.0,Medium,420D,...,20,3,141,False,False,False,False,False,False,1085011200
25,1139351,9.433484,833838,7009,121,3.0,2003,1028.0,Medium,226,...,9,3,68,False,False,False,False,False,False,1141862400
26,1139354,9.648595,565440,7040,121,3.0,2003,356.0,Low,302.5,...,9,3,68,False,False,False,False,False,False,1141862400
27,1139356,10.878047,1004127,25458,121,3.0,2000,0.0,NaN,EX550STD,...,22,3,53,False,False,False,False,False,False,1172102400
28,1139357,10.736397,44800,19167,121,3.0,2004,904.0,Low,685B,...,9,3,221,False,False,False,False,False,False,1186617600
29,1139358,11.396392,1018076,1333,121,3.0,1998,10466.0,Medium,345BL,...,1,3,152,False,True,False,False,False,False,1149120000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401095,6333259,9.259131,1872639,21437,149,1.0,2003,NaN,NaN,35N,...,14,2,348,False,False,False,False,False,False,1323820800
401096,6333260,9.210340,1816341,21437,149,2.0,2004,NaN,NaN,35N,...,15,3,258,False,False,False,False,False,False,1316044800
401097,6333261,9.047821,1843949,21437,149,1.0,2005,NaN,NaN,35N,...,28,4,301,False,False,False,False,False,False,1319760000
401098,6333262,9.259131,1791341,21437,149,2.0,2004,NaN,NaN,35N,...,16,1,228,False,False,False,False,False,False,1313452800
401099,6333263,9.305651,1833174,21437,149,1.0,2004,NaN,NaN,35N,...,14,2,348,False,False,False,False,False,False,1323820800
401100,6333264,9.259131,1791370,21437,149,2.0,2004,NaN,NaN,35N,...,16,1,228,False,False,False,False,False,False,1313452800
401101,6333270,9.210340,1799208,21437,149,1.0,2004,NaN,NaN,35N,...,14,2,348,False,False,False,False,False,False,1323820800
401102,6333272,9.259131,1927142,21437,149,2.0,2005,NaN,NaN,35N,...,16,1,228,False,False,False,False,False,False,1313452800
401103,6333273,9.433484,1789856,21437,149,2.0,2005,NaN,NaN,35N,...,15,3,258,False,False,False,False,False,False,1316044800
401104,6333275,9.259131,1924623,21437,149,2.0,2005,NaN,NaN,35N,...,16,1,228,False,False,False,False,False,False,1313452800
401105,6333276,9.210340,1835350,21437,149,2.0,2005,NaN,NaN,35N,...,25,1,298,False,False,False,False,False,False,1319500800
401106,6333278,9.259131,1944702,21437,149,2.0,2005,NaN,NaN,35N,...,16,1,228,False,False,False,False,False,False,1313452800
401107,6333279,9.433484,1866563,21437,149,2.0,2005,NaN,NaN,35N,...,15,3,258,False,False,False,False,False,False,1316044800
401108,6333280,9.259131,1851633,21437,149,2.0,2005,NaN,NaN,35N,...,16,1,228,False,False,False,False,False,False,1313452800
401109,6333281,9.259131,1798958,21437,149,2.0,2005,NaN,NaN,35N,...,16,1,228,False,False,False,False,False,False,1313452800
401110,6333282,9.259131,1878866,21437,149,2.0,2005,NaN,NaN,35N,...,15,3,258,False,False,False,False,False,False,1316044800
401111,6333283,9.210340,1874235,21437,149,2.0,2005,NaN,NaN,35N,...,25,1,298,False,False,False,False,False,False,1319500800
401112,6333284,9.259131,1887654,21437,149,2.0,2005,NaN,NaN,35N,...,25,1,298,False,False,False,False,False,False,1319500800
401113,6333285,9.259131,1817165,21437,149,2.0,2005,NaN,NaN,35N,...,25,1,298,False,False,False,False,False,False,1319500800
401114,6333287,9.433484,1918242,21437,149,2.0,2005,NaN,NaN,35N,...,15,1,319,False,False,False,False,False,False,1321315200
401115,6333290,9.210340,1843374,21437,149,2.0,2005,NaN,NaN,35N,...,25,1,298,False,False,False,False,False,False,1319500800
401116,6333302,9.047821,1825337,21437,149,2.0,2005,NaN,NaN,35N,...,25,1,298,False,False,False,False,False,False,1319500800
401117,6333307,9.210340,1821747,21437,149,2.0,2005,NaN,NaN,35N,...,25,1,298,False,False,False,False,False,False,1319500800
401118,6333311,9.159047,1828862,21437,149,2.0,2006,NaN,NaN,35N,...,25,1,298,False,False,False,False,False,False,1319500800
401119,6333335,9.047821,1798293,21435,149,2.0,2005,NaN,NaN,30NX,...,25,1,298,False,False,False,False,False,False,1319500800
401120,6333336,9.259131,1840702,21439,149,1.0,2005,NaN,NaN,35NX2,...,2,2,306,False,False,False,False,False,False,1320192000
401121,6333337,9.305651,1830472,21439,149,1.0,2005,NaN,NaN,35NX2,...,2,2,306,False,False,False,False,False,False,1320192000
401122,6333338,9.350102,1887659,21439,149,1.0,2005,NaN,NaN,35NX2,...,2,2,306,False,False,False,False,False,False,1320192000
401123,6333341,9.104980,1903570,21435,149,2.0,2005,NaN,NaN,30NX,...,25,1,298,False,False,False,False,False,False,1319500800
401124,6333342,8.955448,1926965,21435,149,2.0,2005,NaN,NaN,30NX,...,25,1,298,False,False,False,False,False,False,1319500800

In [71]:
df_raw.UsageBand.cat.categories

Index(['High', 'Low', 'Medium'], dtype='object')

In [0]:
df_raw.UsageBand.cat.set_categories(['High', 'Medium', 'Low'], ordered=True, inplace=True)

In [0]:
df_raw.UsageBand = df_raw.UsageBand.cat.codes

In [81]:
display_all(df_raw.isnull().sum().sort_index()/len(df_raw))

Backhoe_Mounting            0.803872
Blade_Extension             0.937129
Blade_Type                  0.800977
Blade_Width                 0.937129
Coupler                     0.466620
Coupler_System              0.891660
Differential_Type           0.826959
Drive_System                0.739829
Enclosure                   0.000810
Enclosure_Type              0.937129
Engine_Horsepower           0.937129
Forks                       0.521154
Grouser_Tracks              0.891899
Grouser_Type                0.752813
Hydraulics                  0.200823
Hydraulics_Flow             0.891899
MachineHoursCurrentMeter    0.644089
MachineID                   0.000000
ModelID                     0.000000
Pad_Type                    0.802720
Pattern_Changer             0.752651
ProductGroup                0.000000
ProductGroupDesc            0.000000
ProductSize                 0.525460
Pushblock                   0.937129
Ride_Control                0.629527
Ripper                      0.740388
SalePrice                   0.000000
SalesID                     0.000000
Scarifier                   0.937102
Steering_Controls           0.827064
Stick                       0.802720
Stick_Length                0.752651
Thumb                       0.752476
Tip_Control                 0.937129
Tire_Size                   0.763869
Track_Type                  0.752813
Transmission                0.543210
Travel_Controls             0.800975
Turbocharged                0.802720
Undercarriage_Pad_Width     0.751020
UsageBand                   0.000000
YearMade                    0.000000
auctioneerID                0.050199
datasource                  0.000000
fiBaseModel                 0.000000
fiModelDesc                 0.000000
fiModelDescriptor           0.820707
fiModelSeries               0.858129
fiProductClassDesc          0.000000
fiSecondaryDesc             0.342016
saleDay                     0.000000
saleDayofweek               0.000000
saleDayofyear               0.000000
saleElapsed                 0.000000
saleIs_month_end            0.000000
saleIs_month_start          0.000000
saleIs_quarter_end          0.000000
saleIs_quarter_start        0.000000
saleIs_year_end             0.000000
saleIs_year_start           0.000000
saleMonth                   0.000000
saleWeek                    0.000000
saleYear                    0.000000
state                       0.000000
dtype: float64

In [0]:
os.makedirs('tmp', exist_ok=True)
df_raw.to_feather('tmp/bulldozers-raw')

In [85]:
df_raw = pd.read_feather('tmp/bulldozers-raw')

/usr/local/lib/python3.6/dist-packages/pandas/io/feather_format.py:112: FutureWarning: `nthreads` argument is deprecated, pass `use_threads` instead
  return feather.read_dataframe(path, nthreads=nthreads)

In [0]:
df,y,nas = proc_df(df_raw,'SalePrice')

In [92]:
y, nas

(array([11.09741, 10.95081,  9.21034, ...,  9.3501 ,  9.10498,  8.95545]),
 {'MachineHoursCurrentMeter': 0.0, 'auctioneerID': 2.0})

In [90]:
df

,SalesID,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,fiModelDesc,fiBaseModel,...,saleDayofyear,saleIs_month_end,saleIs_month_start,saleIs_quarter_end,saleIs_quarter_start,saleIs_year_end,saleIs_year_start,saleElapsed,auctioneerID_na,MachineHoursCurrentMeter_na
0,1139246,999089,3157,121,3.0,2004,68.0,2,950,296,...,320,False,False,False,False,False,False,1163635200,False,False
1,1139248,117657,77,121,3.0,1996,4640.0,2,1725,527,...,86,False,False,False,False,False,False,1080259200,False,False
2,1139249,434808,7009,121,3.0,2001,2838.0,0,331,110,...,57,False,False,False,False,False,False,1077753600,False,False
3,1139251,1026470,332,121,3.0,2001,3486.0,0,3674,1375,...,139,False,False,False,False,False,False,1305763200,False,False
4,1139253,1057373,17311,121,3.0,2007,722.0,1,4208,1529,...,204,False,False,False,False,False,False,1248307200,False,False
5,1139255,1001274,4605,121,3.0,2004,508.0,2,493,175,...,353,False,False,False,False,False,False,1229558400,False,False
6,1139256,772701,1937,121,3.0,1993,11540.0,0,1453,419,...,239,False,False,False,False,False,False,1093478400,False,False
7,1139261,902002,3539,121,3.0,2001,4883.0,0,740,243,...,321,False,False,False,False,False,False,1132185600,False,False
8,1139272,1036251,36003,121,3.0,2008,302.0,2,779,250,...,239,False,False,False,False,False,False,1251331200,False,False
9,1139275,1016474,3883,121,3.0,1000,20700.0,1,1771,540,...,221,False,False,False,False,False,False,1186617600,False,False
10,1139278,1024998,4605,121,3.0,2004,1414.0,1,493,175,...,234,False,False,False,False,False,False,1219276800,False,False
11,1139282,319906,5255,121,3.0,1998,2764.0,2,2028,683,...,236,False,False,False,False,False,False,1156377600,False,False
12,1139283,1052214,2232,121,3.0,1998,0.0,-1,3761,1388,...,293,False,False,False,False,False,False,1129766400,False,False
13,1139284,1068082,3542,121,3.0,2001,1921.0,1,747,245,...,26,False,False,False,False,False,False,1138233600,False,False
14,1139290,1058450,5162,121,3.0,2004,320.0,2,274,100,...,3,False,False,False,False,False,False,1136246400,False,False
15,1139291,1004810,4604,121,3.0,1999,2450.0,1,491,175,...,320,False,False,False,False,False,False,1163635200,False,False
16,1139292,1026973,9510,121,3.0,1999,1972.0,2,612,199,...,165,False,False,False,False,False,False,1181779200,False,False
17,1139299,1002713,21442,121,3.0,2003,0.0,-1,878,264,...,28,False,False,False,False,False,False,1264636800,False,False
18,1139301,125790,7040,121,3.0,2001,994.0,2,451,166,...,68,False,False,False,False,False,False,1141862400,False,False
19,1139304,1011914,3177,121,3.0,1991,8005.0,1,1073,324,...,321,False,False,False,False,False,False,1132185600,False,False
20,1139311,1014135,8867,121,3.0,2000,3259.0,1,3127,1058,...,138,False,False,False,False,False,False,1147910400,False,False
21,1139333,999192,3350,121,3.0,1000,16328.0,1,67,20,...,292,False,False,False,False,False,False,1161216000,False,False
22,1139344,1044500,7040,121,3.0,2005,109.0,2,451,166,...,298,False,False,False,False,False,False,1193270400,False,False
23,1139346,821452,85,121,3.0,1996,17033.0,0,1751,533,...,292,False,False,False,False,False,False,1161216000,False,False
24,1139348,294562,3542,121,3.0,2001,1877.0,1,747,245,...,141,False,False,False,False,False,False,1085011200,False,False
25,1139351,833838,7009,121,3.0,2003,1028.0,1,331,110,...,68,False,False,False,False,False,False,1141862400,False,False
26,1139354,565440,7040,121,3.0,2003,356.0,2,451,166,...,68,False,False,False,False,False,False,1141862400,False,False
27,1139356,1004127,25458,121,3.0,2000,0.0,-1,2741,852,...,53,False,False,False,False,False,False,1172102400,False,False
28,1139357,44800,19167,121,3.0,2004,904.0,2,1260,371,...,221,False,False,False,False,False,False,1186617600,False,False
29,1139358,1018076,1333,121,3.0,1998,10466.0,1,633,206,...,152,False,True,False,False,False,False,1149120000,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401095,6333259,1872639,21437,149,1.0,2003,0.0,-1,655,207,...,348,False,False,False,False,False,False,1323820800,False,True
401096,6333260,1816341,21437,149,2.0,2004,0.0,-1,655,207,...,258,False,False,False,False,False,False,1316044800,False,True
401097,6333261,1843949,21437,149,1.0,2005,0.0,-1,655,207,...,301,False,False,False,False,False,False,1319760000,False,True
401098,6333262,1791341,21437,149,2.0,2004,0.0,-1,655,207,...,228,False,False,False,False,False,False,1313452800,False,True
401099,6333263,1833174,21437,149,1.0,2004,0.0,-1,655,207,...,348,False,False,False,False,False,False,1323820800,False,True
401100,6333264,1791370,21437,149,2.0,2004,0.0,-1,655,207,...,228,False,False,False,False,False,False,1313452800,False,True
401101,6333270,1799208,21437,149,1.0,2004,0.0,-1,655,207,...,348,False,False,False,False,False,False,1323820800,False,True
401102,6333272,1927142,21437,149,2.0,2005,0.0,-1,655,207,...,228,False,False,False,False,False,False,1313452800,False,True
401103,6333273,1789856,21437,149,2.0,2005,0.0,-1,655,207,...,258,False,False,False,False,False,False,1316044800,False,True
401104,6333275,1924623,21437,149,2.0,2005,0.0,-1,655,207,...,228,False,False,False,False,False,False,1313452800,False,True
401105,6333276,1835350,21437,149,2.0,2005,0.0,-1,655,207,...,298,False,False,False,False,False,False,1319500800,False,True
401106,6333278,1944702,21437,149,2.0,2005,0.0,-1,655,207,...,228,False,False,False,False,False,False,1313452800,False,True
401107,6333279,1866563,21437,149,2.0,2005,0.0,-1,655,207,...,258,False,False,False,False,False,False,1316044800,False,True
401108,6333280,1851633,21437,149,2.0,2005,0.0,-1,655,207,...,228,False,False,False,False,False,False,1313452800,False,True
401109,6333281,1798958,21437,149,2.0,2005,0.0,-1,655,207,...,228,False,False,False,False,False,False,1313452800,False,True
401110,6333282,1878866,21437,149,2.0,2005,0.0,-1,655,207,...,258,False,False,False,False,False,False,1316044800,False,True
401111,6333283,1874235,21437,149,2.0,2005,0.0,-1,655,207,...,298,False,False,False,False,False,False,1319500800,False,True
401112,6333284,1887654,21437,149,2.0,2005,0.0,-1,655,207,...,298,False,False,False,False,False,False,1319500800,False,True
401113,6333285,1817165,21437,149,2.0,2005,0.0,-1,655,207,...,298,False,False,False,False,False,False,1319500800,False,True
401114,6333287,1918242,21437,149,2.0,2005,0.0,-1,655,207,...,319,False,False,False,False,False,False,1321315200,False,True
401115,6333290,1843374,21437,149,2.0,2005,0.0,-1,655,207,...,298,False,False,False,False,False,False,1319500800,False,True
401116,6333302,1825337,21437,149,2.0,2005,0.0,-1,655,207,...,298,False,False,False,False,False,False,1319500800,False,True
401117,6333307,1821747,21437,149,2.0,2005,0.0,-1,655,207,...,298,False,False,False,False,False,False,1319500800,False,True
401118,6333311,1828862,21437,149,2.0,2006,0.0,-1,655,207,...,298,False,False,False,False,False,False,1319500800,False,True
401119,6333335,1798293,21435,149,2.0,2005,0.0,-1,483,159,...,298,False,False,False,False,False,False,1319500800,False,True
401120,6333336,1840702,21439,149,1.0,2005,0.0,-1,657,207,...,306,False,False,False,False,False,False,1320192000,False,True
401121,6333337,1830472,21439,149,1.0,2005,0.0,-1,657,207,...,306,False,False,False,False,False,False,1320192000,False,True
401122,6333338,1887659,21439,149,1.0,2005,0.0,-1,657,207,...,306,False,False,False,False,False,False,1320192000,False,True
401123,6333341,1903570,21435,149,2.0,2005,0.0,-1,483,159,...,298,False,False,False,False,False,False,1319500800,False,True
401124,6333342,1926965,21435,149,2.0,2005,0.0,-1,483,159,...,298,False,False,False,False,False,False,1319500800,False,True

In [0]:
m = RandomForestClassifier(n_jobs=-1)

In [93]:
m.fit(df,y)

ValueError: ignored

In [0]:
m.score(df,y)

In [94]:
df.

Index(['SalesID', 'MachineID', 'ModelID', 'datasource', 'auctioneerID',
       'YearMade', 'MachineHoursCurrentMeter', 'UsageBand', 'fiModelDesc',
       'fiBaseModel', 'fiSecondaryDesc', 'fiModelSeries', 'fiModelDescriptor',
       'ProductSize', 'fiProductClassDesc', 'state', 'ProductGroup',
       'ProductGroupDesc', 'Drive_System', 'Enclosure', 'Forks', 'Pad_Type',
       'Ride_Control', 'Stick', 'Transmission', 'Turbocharged',
       'Blade_Extension', 'Blade_Width', 'Enclosure_Type', 'Engine_Horsepower',
       'Hydraulics', 'Pushblock', 'Ripper', 'Scarifier', 'Tip_Control',
       'Tire_Size', 'Coupler', 'Coupler_System', 'Grouser_Tracks',
       'Hydraulics_Flow', 'Track_Type', 'Undercarriage_Pad_Width',
       'Stick_Length', 'Thumb', 'Pattern_Changer', 'Grouser_Type',
       'Backhoe_Mounting', 'Blade_Type', 'Travel_Controls',
       'Differential_Type', 'Steering_Controls', 'saleYear', 'saleMonth',
       'saleWeek', 'saleDay', 'saleDayofweek', 'saleDayofyear',
       'saleIs_month_end', 'saleIs_month_start', 'saleIs_quarter_end',
       'saleIs_quarter_start', 'saleIs_year_end', 'saleIs_year_start',
       'saleElapsed', 'auctioneerID_na', 'MachineHoursCurrentMeter_na'],
      dtype='object')