[View in Colaboratory](https://colab.research.google.com/github/desirajusantosh/DS/blob/master/random_forests_1.ipynb)

Random Forests

In [124]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [0]:
autoreload 2

In [0]:
%matplotlib inline

In [127]:
!pip install fastai==0.7.0
from fastai.imports import *

Requirement already satisfied: fastai==0.7.0 in /usr/local/lib/python3.6/dist-packages (0.7.0)
Requirement already satisfied: traitlets in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (4.3.2)
Requirement already satisfied: pyzmq in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (16.0.4)
Requirement already satisfied: Pygments in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2.1.3)
Requirement already satisfied: feather-format in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.22.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.7.1)
Requirement already satisfied: sklearn-pandas in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (1.7.0)
Requirement already satisfied: html5lib in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (1.0.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.7.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2.1.2)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2.6.0)
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2.10)
Requirement already satisfied: bcolz in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (1.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (4.26.0)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (7.4.2)
Requirement already satisfied: isoweek in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (1.3.3)
Requirement already satisfied: simplegeneric in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.8.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.1.7)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (1.0)
Requirement already satisfied: widgetsnbextension in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (3.4.2)
Requirement already satisfied: jedi in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.13.1)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2.2.1)
Requirement already satisfied: torch<0.4 in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.3.1)
Requirement already satisfied: cycler in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.10.0)
Requirement already satisfied: torchvision in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.2.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (1.14.6)
Requirement already satisfied: torchtext in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.2.3)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.2.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.9)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2.5.3)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.5.1)
Requirement already satisfied: ipython in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (5.5.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.6.0)
Requirement already satisfied: testpath in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.4.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2018.8.24)
Requirement already satisfied: pandas-summary in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.0.5)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2018.5)
Requirement already satisfied: jupyter in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (1.0.0)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (3.4.3.18)
Requirement already satisfied: Pillow in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (4.0.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (2.1.4)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (4.3.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (4.6.1)
Requirement already satisfied: plotnine in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (3.13)
Requirement already satisfied: tornado in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (4.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from fastai==0.7.0) (0.19.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from traitlets->fastai==0.7.0) (1.11.0)
Requirement already satisfied: pyarrow>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from feather-format->fastai==0.7.0) (0.10.0)
Requirement already satisfied: scikit-learn>=0.15.0 in /usr/local/lib/python3.6/dist-packages (from sklearn-pandas->fastai==0.7.0) (0.19.2)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.6/dist-packages (from ipywidgets->fastai==0.7.0) (4.4.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.6/dist-packages (from widgetsnbextension->fastai==0.7.0) (5.2.2)
Requirement already satisfied: parso>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from jedi->fastai==0.7.0) (0.3.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from torchtext->fastai==0.7.0) (2.18.4)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from ipython->fastai==0.7.0) (1.0.15)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/dist-packages (from ipython->fastai==0.7.0) (39.1.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from ipython->fastai==0.7.0) (4.6.0)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.6/dist-packages (from jupyter->fastai==0.7.0) (5.4.0)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.6/dist-packages (from jupyter->fastai==0.7.0) (5.2.0)
Requirement already satisfied: qtconsole in /usr/local/lib/python3.6/dist-packages (from jupyter->fastai==0.7.0) (4.4.1)
Requirement already satisfied: olefile in /usr/local/lib/python3.6/dist-packages (from Pillow->fastai==0.7.0) (0.46)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.6/dist-packages (from ipykernel->fastai==0.7.0) (5.2.3)
Requirement already satisfied: geopandas>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai==0.7.0) (0.4.0)
Requirement already satisfied: mizani>=0.4.5 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai==0.7.0) (0.4.6)
Requirement already satisfied: patsy>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai==0.7.0) (0.5.0)
Requirement already satisfied: descartes>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai==0.7.0) (1.1.0)
Requirement already satisfied: statsmodels>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from plotnine->fastai==0.7.0) (0.8.0)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.6/dist-packages (from nbformat>=4.2.0->ipywidgets->fastai==0.7.0) (4.4.0)
Requirement already satisfied: terminado>=0.3.3; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from notebook>=4.4.1->widgetsnbextension->fastai==0.7.0) (0.8.1)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->torchtext->fastai==0.7.0) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->torchtext->fastai==0.7.0) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->torchtext->fastai==0.7.0) (3.0.4)
Requirement already satisfied: mistune>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->jupyter->fastai==0.7.0) (0.8.3)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.6/dist-packages (from nbconvert->jupyter->fastai==0.7.0) (0.5.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from nbconvert->jupyter->fastai==0.7.0) (1.4.2)
Requirement already satisfied: shapely in /usr/local/lib/python3.6/dist-packages (from geopandas>=0.3.0->plotnine->fastai==0.7.0) (1.6.4.post2)
Requirement already satisfied: pyproj in /usr/local/lib/python3.6/dist-packages (from geopandas>=0.3.0->plotnine->fastai==0.7.0) (1.9.5.1)
Requirement already satisfied: fiona in /usr/local/lib/python3.6/dist-packages (from geopandas>=0.3.0->plotnine->fastai==0.7.0) (1.7.13)
Requirement already satisfied: palettable in /usr/local/lib/python3.6/dist-packages (from mizani>=0.4.5->plotnine->fastai==0.7.0) (3.1.1)
Requirement already satisfied: cligj>=0.4 in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas>=0.3.0->plotnine->fastai==0.7.0) (0.5.0)
Requirement already satisfied: munch in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas>=0.3.0->plotnine->fastai==0.7.0) (2.3.2)
Requirement already satisfied: click-plugins in /usr/local/lib/python3.6/dist-packages (from fiona->geopandas>=0.3.0->plotnine->fastai==0.7.0) (1.0.4)
Requirement already satisfied: click<8,>=4.0 in /usr/local/lib/python3.6/dist-packages (from cligj>=0.4->fiona->geopandas>=0.3.0->plotnine->fastai==0.7.0) (7.0)

In [0]:
from fastai.imports import *

In [0]:
from fastai.structured import *

In [0]:
from pandas_summary import DataFrameSummary

In [0]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [0]:
from IPython.display import display

In [0]:
from sklearn import metrics

In [134]:
!kaggle competitions download -c bluebook-for-bulldozers

Train.7z: Skipping, found more recently modified local copy (use --force to force download)
Train.zip: Skipping, found more recently modified local copy (use --force to force download)
Valid.7z: Skipping, found more recently modified local copy (use --force to force download)
Valid.csv: Skipping, found more recently modified local copy (use --force to force download)
Valid.zip: Skipping, found more recently modified local copy (use --force to force download)
Data%20Dictionary.xlsx: Skipping, found more recently modified local copy (use --force to force download)
median_benchmark.csv: Skipping, found more recently modified local copy (use --force to force download)
Machine_Appendix.csv: Skipping, found more recently modified local copy (use --force to force download)
ValidSolution.csv: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.7z: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.csv: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.zip: Skipping, found more recently modified local copy (use --force to force download)
Test.csv: Skipping, found more recently modified local copy (use --force to force download)
random_forest_benchmark_test.csv: Skipping, found more recently modified local copy (use --force to force download)

In [135]:
!pip install git+https://github.com/floydwch/kaggle-cli.git

Collecting git+https://github.com/floydwch/kaggle-cli.git
  Cloning https://github.com/floydwch/kaggle-cli.git to /tmp/pip-req-build-vnxjci0o
Requirement already satisfied (use --upgrade to upgrade): kaggle-cli==0.13.0 from git+https://github.com/floydwch/kaggle-cli.git in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: cliff<2.9,>=2.8.0 in /usr/local/lib/python3.6/dist-packages (from kaggle-cli==0.13.0) (2.8.2)
Requirement already satisfied: MechanicalSoup<0.9,>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from kaggle-cli==0.13.0) (0.8.0)
Requirement already satisfied: lxml<4.1,>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from kaggle-cli==0.13.0) (4.0.0)
Requirement already satisfied: cssselect<1.1,>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from kaggle-cli==0.13.0) (1.0.3)
Requirement already satisfied: configparser in /usr/local/lib/python3.6/dist-packages (from kaggle-cli==0.13.0) (3.5.0)
Requirement already satisfied: progressbar2<3.35,>=3.34.3 in /usr/local/lib/python3.6/dist-packages (from kaggle-cli==0.13.0) (3.34.3)
Requirement already satisfied: beautifulsoup4<4.7,>=4.6.0 in /usr/local/lib/python3.6/dist-packages (from kaggle-cli==0.13.0) (4.6.3)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (4.2.0)
Requirement already satisfied: stevedore>=1.20.0 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (1.29.0)
Requirement already satisfied: pyparsing>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (2.2.1)
Requirement already satisfied: PrettyTable<0.8,>=0.7.1 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (0.7.2)
Requirement already satisfied: PyYAML>=3.10.0 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (3.13)
Requirement already satisfied: cmd2>=0.6.7; python_version >= "3.0" in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (0.9.4)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (1.11.0)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python3.6/dist-packages (from MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (2.18.4)
Requirement already satisfied: python-utils>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from progressbar2<3.35,>=3.34.3->kaggle-cli==0.13.0) (2.3.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.6/dist-packages (from cmd2>=0.6.7; python_version >= "3.0"->cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (0.3.9)
Requirement already satisfied: pyperclip>=1.5.27 in /usr/local/lib/python3.6/dist-packages (from cmd2>=0.6.7; python_version >= "3.0"->cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (1.7.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.6/dist-packages (from cmd2>=0.6.7; python_version >= "3.0"->cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (18.2.0)
Requirement already satisfied: wcwidth; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from cmd2>=0.6.7; python_version >= "3.0"->cliff<2.9,>=2.8.0->kaggle-cli==0.13.0) (0.1.7)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (2018.8.24)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.0->MechanicalSoup<0.9,>=0.7.0->kaggle-cli==0.13.0) (3.0.4)
Building wheels for collected packages: kaggle-cli
  Running setup.py bdist_wheel for kaggle-cli ... - \ done
  Stored in directory: /tmp/pip-ephem-wheel-cache-d2tn83m4/wheels/c2/d0/54/64709fb6e7766205e35b5f27e0ecd63a7ae179cadd44d14845
Successfully built kaggle-cli

In [136]:
!kaggle competitions download -c bluebook-for-bulldozers -u santosh7

usage: kaggle [-h] [-v] {competitions,c,datasets,d,kernels,k,config} ...
kaggle: error: unrecognized arguments: -u

In [137]:
!kaggle config -g -u ‘santosh7’ -p ‘Kaggle2015’ -c ‘bluebook-for-bulldozers’

usage: kaggle config [-h] {view,set,unset} ...
kaggle config: error: argument command: invalid choice: '‘santosh7’' (choose from 'view', 'set', 'unset')

In [138]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.6/dist-packages (1.4.7.1)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.11.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.2.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from kaggle) (4.26.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from kaggle) (2.5.3)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from kaggle) (2.18.4)
Requirement already satisfied: urllib3<1.23.0,>=1.15 in /usr/local/lib/python3.6/dist-packages (from kaggle) (1.22)
Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from kaggle) (2018.8.24)
Requirement already satisfied: Unidecode>=0.04.16 in /usr/local/lib/python3.6/dist-packages (from python-slugify->kaggle) (1.0.22)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->kaggle) (3.0.4)

In [139]:
!ls sample_data/

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md

In [140]:
!kaggle competitions download -c bluebook-for-bulldozers

Train.7z: Skipping, found more recently modified local copy (use --force to force download)
Train.zip: Skipping, found more recently modified local copy (use --force to force download)
Valid.7z: Skipping, found more recently modified local copy (use --force to force download)
Valid.csv: Skipping, found more recently modified local copy (use --force to force download)
Valid.zip: Skipping, found more recently modified local copy (use --force to force download)
Data%20Dictionary.xlsx: Skipping, found more recently modified local copy (use --force to force download)
median_benchmark.csv: Skipping, found more recently modified local copy (use --force to force download)
Machine_Appendix.csv: Skipping, found more recently modified local copy (use --force to force download)
ValidSolution.csv: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.7z: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.csv: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.zip: Skipping, found more recently modified local copy (use --force to force download)
Test.csv: Skipping, found more recently modified local copy (use --force to force download)
random_forest_benchmark_test.csv: Skipping, found more recently modified local copy (use --force to force download)

In [141]:
cp /root/.kaggle-cli/config /root/.kaggle/kaggle.json

cp: cannot stat '/root/.kaggle-cli/config': No such file or directory

In [142]:
!kaggle competitions download -c bluebook-for-bulldozers

Train.7z: Skipping, found more recently modified local copy (use --force to force download)
Train.zip: Skipping, found more recently modified local copy (use --force to force download)
Valid.7z: Skipping, found more recently modified local copy (use --force to force download)
Valid.csv: Skipping, found more recently modified local copy (use --force to force download)
Valid.zip: Skipping, found more recently modified local copy (use --force to force download)
Data%20Dictionary.xlsx: Skipping, found more recently modified local copy (use --force to force download)
median_benchmark.csv: Skipping, found more recently modified local copy (use --force to force download)
Machine_Appendix.csv: Skipping, found more recently modified local copy (use --force to force download)
ValidSolution.csv: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.7z: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.csv: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.zip: Skipping, found more recently modified local copy (use --force to force download)
Test.csv: Skipping, found more recently modified local copy (use --force to force download)
random_forest_benchmark_test.csv: Skipping, found more recently modified local copy (use --force to force download)

In [143]:
!head /root/.kaggle/kaggle.json

{"username": "santosh7", "key": "422fdad87a7bb7199b50f3807d828147"}

In [144]:
!kaggle datasets list

ref                                                      title                                         size  lastUpdated          downloadCount
-------------------------------------------------------  -------------------------------------------  -----  -------------------  -------------
lava18/google-play-store-apps                            Google Play Store Apps                         2MB  2018-09-18 20:49:49           5528
neuromusic/avocado-prices                                Avocado Prices                               629KB  2018-06-06 05:28:35           8946
blastchar/telco-customer-churn                           Telco Customer Churn                         172KB  2018-02-23 18:20:00           7101
bigquery/patents                                         Google Patents Public Data                     2TB  2018-09-19 01:57:26              0
san-francisco/sf-police-calls-for-service-and-incidents  SF Police Calls for Service and Incidents    165MB  2018-10-02 09:35:42            824
lucidlenn/sloan-digital-sky-survey                       Sloan Digital Sky Survey RD14                446KB  2018-09-20 00:23:41            832
jenny18/honey-bee-annotated-images                       Annotated Honey Bee Images                    50MB  2018-09-16 23:42:12            486
census/census-bureau-usa                                 United States Census                         161MB  2018-04-17 18:52:46              0
census/total-business-inventories-and-sales-data         Total Business Inventories and Sales Data     21KB  2018-10-02 20:31:34            435
chicago/chicago-311-service-requests                     Chicago 311 Service Requests                 232MB  2018-10-02 16:08:44            287
cityofLA/la-restaurant-market-health-data                LA Restaurant & Market Health Data            10MB  2018-09-06 05:37:59           2206
cityofLA/los-angeles-metro-bike-share-trip-data          Los Angeles Metro Bike Share Trip Data         3MB  2018-09-06 06:37:25           1153
fmena14/volcanoesvenus                                   Volcanoes on Venus                           109MB  2018-08-25 01:37:34            296
kevinarvai/clinvar-conflicting                           Genetic Variant Classifications                3MB  2018-04-22 19:16:07           1583
chicago/chicago-red-light-and-speed-camera-data          Chicago Red Light and Speed Camera Data       22MB  2018-10-02 16:41:44            442
kmader/nih-deeplesion-subset                             NIH DeepLesion Subset                          8GB  2018-07-22 18:58:32            252
crawford/boston-public-schools                           Boston Public Schools                         21KB  2018-09-18 21:49:50            308
smid80/weatherww2                                        Weather Conditions in World War Two            2MB  2017-11-01 05:05:30           3028
marklvl/bike-sharing-dataset                             Bike Sharing in Washington D.C. Dataset      273KB  2018-05-28 11:31:09           1886
census/family-households-with-married-couples-data       Family Households with Married Couples Data    2KB  2018-10-02 20:38:58            241

In [145]:
!head /content/.kaggle/kaggle.json

{"username": "santosh7", "key": "422fdad87a7bb7199b50f3807d828147"}

In [0]:
import json

In [0]:
token = {"username":"santosh7","key":"422fdad87a7bb7199b50f3807d828147"}

In [148]:
!mkdir /content/.kaggle
!touch /content/.kaggle/kaggle.json
with open("/content/.kaggle/kaggle.json", "w") as file:
  json.dump(token,file)

mkdir: cannot create directory ‘/content/.kaggle’: File exists

In [0]:
!chmod 600 /content/.kaggle/kaggle.json
!cp /content/.kaggle/kaggle.json ~/.kaggle/kaggle.json

In [150]:
!kaggle competitions download -c bluebook-for-bulldozers

Train.7z: Skipping, found more recently modified local copy (use --force to force download)
Train.zip: Skipping, found more recently modified local copy (use --force to force download)
Valid.7z: Skipping, found more recently modified local copy (use --force to force download)
Valid.csv: Skipping, found more recently modified local copy (use --force to force download)
Valid.zip: Skipping, found more recently modified local copy (use --force to force download)
Data%20Dictionary.xlsx: Skipping, found more recently modified local copy (use --force to force download)
median_benchmark.csv: Skipping, found more recently modified local copy (use --force to force download)
Machine_Appendix.csv: Skipping, found more recently modified local copy (use --force to force download)
ValidSolution.csv: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.7z: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.csv: Skipping, found more recently modified local copy (use --force to force download)
TrainAndValid.zip: Skipping, found more recently modified local copy (use --force to force download)
Test.csv: Skipping, found more recently modified local copy (use --force to force download)
random_forest_benchmark_test.csv: Skipping, found more recently modified local copy (use --force to force download)

In [151]:
!ls

Data%20Dictionary.xlsx		  tmp		     Train.zip
Machine_Appendix.csv		  Train.7z	     Valid.7z
median_benchmark.csv		  TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data			  TrainAndValid.zip  Valid.zip
Test.csv			  Train.csv

In [152]:
!pwd

/content

In [0]:
PATH = "~/content/"

In [0]:
!gzip Train.zip

In [155]:
ls

Data%20Dictionary.xlsx            tmp/               Train.zip.gz
Machine_Appendix.csv              Train.7z           Valid.7z
median_benchmark.csv              TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data/                      TrainAndValid.zip  Valid.zip
Test.csv                          Train.csv

In [0]:
!gunzip Train.zip.gz

In [157]:
!ls

Data%20Dictionary.xlsx		  tmp		     Train.zip
Machine_Appendix.csv		  Train.7z	     Valid.7z
median_benchmark.csv		  TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data			  TrainAndValid.zip  Valid.zip
Test.csv			  Train.csv

In [158]:
!unzip Train.zip

Archive:  Train.zip
replace Train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: Train.csv

In [159]:
!ls -ltr

total 322508
-rw-r--r-- 1 root root 116403970 Jan 24  2013 Train.csv
drwxr-xr-x 2 root root      4096 Sep 28 23:32 sample_data
-rw-r--r-- 1 root root   7183499 Oct  2 23:51 Train.7z
-rw-r--r-- 1 root root   9732240 Oct  2 23:51 Train.zip
-rw-r--r-- 1 root root    214480 Oct  2 23:51 Valid.7z
-rw-r--r-- 1 root root   3318969 Oct  2 23:51 Valid.csv
-rw-r--r-- 1 root root    303660 Oct  2 23:51 Valid.zip
-rw-r--r-- 1 root root     11063 Oct  2 23:51 Data%20Dictionary.xlsx
-rw-r--r-- 1 root root    196760 Oct  2 23:51 median_benchmark.csv
-rw-r--r-- 1 root root  51498702 Oct  2 23:51 Machine_Appendix.csv
-rw-r--r-- 1 root root    323524 Oct  2 23:51 ValidSolution.csv
-rw-r--r-- 1 root root   7403772 Oct  2 23:51 TrainAndValid.7z
-rw-r--r-- 1 root root 119791159 Oct  2 23:51 TrainAndValid.csv
-rw-r--r-- 1 root root  10057248 Oct  2 23:51 TrainAndValid.zip
-rw-r--r-- 1 root root   3560907 Oct  2 23:51 Test.csv
-rw-r--r-- 1 root root    211941 Oct  2 23:51 random_forest_benchmark_test.csv
drwxr-xr-x 2 root root      4096 Oct  2 23:54 tmp

In [160]:
PATH = "/content/"
!ls {PATH}

Data%20Dictionary.xlsx		  tmp		     Train.zip
Machine_Appendix.csv		  Train.7z	     Valid.7z
median_benchmark.csv		  TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data			  TrainAndValid.zip  Valid.zip
Test.csv			  Train.csv

In [161]:
ls

Data%20Dictionary.xlsx            tmp/               Train.zip
Machine_Appendix.csv              Train.7z           Valid.7z
median_benchmark.csv              TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data/                      TrainAndValid.zip  Valid.zip
Test.csv                          Train.csv

In [162]:
ls

Data%20Dictionary.xlsx            tmp/               Train.zip
Machine_Appendix.csv              Train.7z           Valid.7z
median_benchmark.csv              TrainAndValid.7z   Valid.csv
random_forest_benchmark_test.csv  TrainAndValid.csv  ValidSolution.csv
sample_data/                      TrainAndValid.zip  Valid.zip
Test.csv                          Train.csv

In [163]:
pwd

'/content'

In [164]:
!head Train.csv

SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,fiModelDesc,fiBaseModel,fiSecondaryDesc,fiModelSeries,fiModelDescriptor,ProductSize,fiProductClassDesc,state,ProductGroup,ProductGroupDesc,Drive_System,Enclosure,Forks,Pad_Type,Ride_Control,Stick,Transmission,Turbocharged,Blade_Extension,Blade_Width,Enclosure_Type,Engine_Horsepower,Hydraulics,Pushblock,Ripper,Scarifier,Tip_Control,Tire_Size,Coupler,Coupler_System,Grouser_Tracks,Hydraulics_Flow,Track_Type,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
1139246,66000,999089,3157,121,3,2004,68,Low,11/16/2006 0:00,521D,521,D,,,,Wheel Loader - 110.0 to 120.0 Horsepower,Alabama,WL,Wheel Loader,,EROPS w AC,None or Unspecified,,None or Unspecified,,,,,,,,2 Valve,,,,,None or Unspecified,None or Unspecified,,,,,,,,,,,,,Standard,Conventional
1139248,57000,117657,77,121,3,1996,4640,Low,3/26/2004 0:00,950FII,950,F,II,,Medium,Wheel Loader - 150.0 to 175.0 Horsepower,North Carolina,WL,Wheel Loader,,EROPS w AC,None or Unspecified,,None or Unspecified,,,,,,,,2 Valve,,,,,23.5,None or Unspecified,,,,,,,,,,,,,Standard,Conventional
1139249,10000,434808,7009,121,3,2001,2838,High,2/26/2004 0:00,226,226,,,,,Skid Steer Loader - 1351.0 to 1601.0 Lb Operating Capacity,New York,SSL,Skid Steer Loaders,,OROPS,None or Unspecified,,,,,,,,,,Auxiliary,,,,,,None or Unspecified,None or Unspecified,None or Unspecified,Standard,,,,,,,,,,,
1139251,38500,1026470,332,121,3,2001,3486,High,5/19/2011 0:00,PC120-6E,PC120,,-6E,,Small,"Hydraulic Excavator, Track - 12.0 to 14.0 Metric Tons",Texas,TEX,Track Excavators,,EROPS w AC,,,,,,,,,,,2 Valve,,,,,,None or Unspecified,,,,,,,,,,,,,,
1139253,11000,1057373,17311,121,3,2007,722,Medium,7/23/2009 0:00,S175,S175,,,,,Skid Steer Loader - 1601.0 to 1751.0 Lb Operating Capacity,New York,SSL,Skid Steer Loaders,,EROPS,None or Unspecified,,,,,,,,,,Auxiliary,,,,,,None or Unspecified,None or Unspecified,None or Unspecified,Standard,,,,,,,,,,,
1139255,26500,1001274,4605,121,3,2004,508,Low,12/18/2008 0:00,310G,310,G,,,,Backhoe Loader - 14.0 to 15.0 Ft Standard Digging Depth,Arizona,BL,Backhoe Loaders,Four Wheel Drive,OROPS,None or Unspecified,None or Unspecified,No,Extended,Powershuttle,None or Unspecified,,,,,,,,,,,,,,,,,,,,,,,,,
1139256,21000,772701,1937,121,3,1993,11540,High,8/26/2004 0:00,790ELC,790,E,,LC,Large / Medium,"Hydraulic Excavator, Track - 21.0 to 24.0 Metric Tons",Florida,TEX,Track Excavators,,EROPS,,,,,,,,,,,Standard,,,,,,None or Unspecified,,,,Steel,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,,,,,
1139261,27000,902002,3539,121,3,2001,4883,High,11/17/2005 0:00,416D,416,D,,,,Backhoe Loader - 14.0 to 15.0 Ft Standard Digging Depth,Illinois,BL,Backhoe Loaders,Four Wheel Drive,OROPS,None or Unspecified,Reversible,No,Standard,Standard,Yes,,,,,,,,,,,,,,,,,,,,,,,,,
1139272,21500,1036251,36003,121,3,2008,302,Low,8/27/2009 0:00,430HAG,430,HAG,,,Mini,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric Tons",Texas,TEX,Track Excavators,,EROPS,,,,,,,,,,,Auxiliary,,,,,,Manual,,,,Rubber,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,,,,,

In [165]:
name = 'Santosh'
f'Hello {name}'

'Hello Santosh'

In [0]:
df_raw= pd.read_csv(f'{PATH}Train.csv', low_memory=False, parse_dates=["saledate"])

In [167]:
df_raw

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,2004-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,2004-02-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,2011-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,2009-07-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1139255,26500,1001274,4605,121,3.0,2004,508.0,Low,2008-12-18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1139256,21000,772701,1937,121,3.0,1993,11540.0,High,2004-08-26,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
7,1139261,27000,902002,3539,121,3.0,2001,4883.0,High,2005-11-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1139272,21500,1036251,36003,121,3.0,2008,302.0,Low,2009-08-27,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
9,1139275,65000,1016474,3883,121,3.0,1000,20700.0,Medium,2007-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
10,1139278,24000,1024998,4605,121,3.0,2004,1414.0,Medium,2008-08-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1139282,22500,319906,5255,121,3.0,1998,2764.0,Low,2006-08-24,...,NaN,NaN,NaN,NaN,NaN,None or Unspecified,PAT,None or Unspecified,NaN,NaN
12,1139283,36000,1052214,2232,121,3.0,1998,0.0,NaN,2005-10-20,...,None or Unspecified,"11' 0""",None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
13,1139284,30500,1068082,3542,121,3.0,2001,1921.0,Medium,2006-01-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1139290,28000,1058450,5162,121,3.0,2004,320.0,Low,2006-01-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1139291,19000,1004810,4604,121,3.0,1999,2450.0,Medium,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1139292,13500,1026973,9510,121,3.0,1999,1972.0,Low,2007-06-14,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
17,1139299,9500,1002713,21442,121,3.0,2003,0.0,NaN,2010-01-28,...,16 inch,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
18,1139301,12500,125790,7040,121,3.0,2001,994.0,Low,2006-03-09,...,None or Unspecified,None or Unspecified,None or Unspecified,Yes,Double,NaN,NaN,NaN,NaN,NaN
19,1139304,11500,1011914,3177,121,3.0,1991,8005.0,Medium,2005-11-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1139311,41000,1014135,8867,121,3.0,2000,3259.0,Medium,2006-05-18,...,32 inch,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
21,1139333,34500,999192,3350,121,3.0,1000,16328.0,Medium,2006-10-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1139344,26000,1044500,7040,121,3.0,2005,109.0,Low,2007-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
23,1139346,73000,821452,85,121,3.0,1996,17033.0,High,2006-10-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
24,1139348,33000,294562,3542,121,3.0,2001,1877.0,Medium,2004-05-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1139351,12500,833838,7009,121,3.0,2003,1028.0,Medium,2006-03-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1139354,15500,565440,7040,121,3.0,2003,356.0,Low,2006-03-09,...,None or Unspecified,None or Unspecified,None or Unspecified,Yes,Double,NaN,NaN,NaN,NaN,NaN
27,1139356,53000,1004127,25458,121,3.0,2000,0.0,NaN,2007-02-22,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
28,1139357,46000,44800,19167,121,3.0,2004,904.0,Low,2007-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1139358,89000,1018076,1333,121,3.0,1998,10466.0,Medium,2006-06-01,...,None or Unspecified,"15' 9""",None or Unspecified,Yes,Double,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401095,6333259,10500,1872639,21437,149,1.0,2003,NaN,NaN,2011-12-14,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401096,6333260,10000,1816341,21437,149,2.0,2004,NaN,NaN,2011-09-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401097,6333261,8500,1843949,21437,149,1.0,2005,NaN,NaN,2011-10-28,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401098,6333262,10500,1791341,21437,149,2.0,2004,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401099,6333263,11000,1833174,21437,149,1.0,2004,NaN,NaN,2011-12-14,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401100,6333264,10500,1791370,21437,149,2.0,2004,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401101,6333270,10000,1799208,21437,149,1.0,2004,NaN,NaN,2011-12-14,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401102,6333272,10500,1927142,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401103,6333273,12500,1789856,21437,149,2.0,2005,NaN,NaN,2011-09-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401104,6333275,10500,1924623,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401105,6333276,10000,1835350,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401106,6333278,10500,1944702,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401107,6333279,12500,1866563,21437,149,2.0,2005,NaN,NaN,2011-09-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401108,6333280,10500,1851633,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401109,6333281,10500,1798958,21437,149,2.0,2005,NaN,NaN,2011-08-16,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401110,6333282,10500,1878866,21437,149,2.0,2005,NaN,NaN,2011-09-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401111,6333283,10000,1874235,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401112,6333284,10500,1887654,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401113,6333285,10500,1817165,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401114,6333287,12500,1918242,21437,149,2.0,2005,NaN,NaN,2011-11-15,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401115,6333290,10000,1843374,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401116,6333302,8500,1825337,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401117,6333307,10000,1821747,21437,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401118,6333311,9500,1828862,21437,149,2.0,2006,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401119,6333335,8500,1798293,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN

In [0]:
def display_all(df):
  with pd.option_context("display.max_rows", 1000, "display.max_columns", 1000):
    display(df)

In [169]:
display_all(df_raw.tail().T)

,401120,401121,401122,401123,401124
SalesID,6333336,6333337,6333338,6333341,6333342
SalePrice,10500,11000,11500,9000,7750
MachineID,1840702,1830472,1887659,1903570,1926965
ModelID,21439,21439,21439,21435,21435
datasource,149,149,149,149,149
auctioneerID,1,1,1,2,2
YearMade,2005,2005,2005,2005,2005
MachineHoursCurrentMeter,NaN,NaN,NaN,NaN,NaN
UsageBand,NaN,NaN,NaN,NaN,NaN
saledate,2011-11-02 00:00:00,2011-11-02 00:00:00,2011-11-02 00:00:00,2011-10-25 00:00:00,2011-10-25 00:00:00
fiModelDesc,35NX2,35NX2,35NX2,30NX,30NX
fiBaseModel,35,35,35,30,30
fiSecondaryDesc,NX,NX,NX,NX,NX
fiModelSeries,2,2,2,NaN,NaN
fiModelDescriptor,NaN,NaN,NaN,NaN,NaN
ProductSize,Mini,Mini,Mini,Mini,Mini
fiProductClassDesc,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 2.0 to 3.0 Metric...","Hydraulic Excavator, Track - 2.0 to 3.0 Metric..."
state,Maryland,Maryland,Maryland,Florida,Florida
ProductGroup,TEX,TEX,TEX,TEX,TEX
ProductGroupDesc,Track Excavators,Track Excavators,Track Excavators,Track Excavators,Track Excavators
Drive_System,NaN,NaN,NaN,NaN,NaN
Enclosure,EROPS,EROPS,EROPS,EROPS,EROPS
Forks,NaN,NaN,NaN,NaN,NaN
Pad_Type,NaN,NaN,NaN,NaN,NaN
Ride_Control,NaN,NaN,NaN,NaN,NaN
Stick,NaN,NaN,NaN,NaN,NaN
Transmission,NaN,NaN,NaN,NaN,NaN
Turbocharged,NaN,NaN,NaN,NaN,NaN
Blade_Extension,NaN,NaN,NaN,NaN,NaN
Blade_Width,NaN,NaN,NaN,NaN,NaN
Enclosure_Type,NaN,NaN,NaN,NaN,NaN
Engine_Horsepower,NaN,NaN,NaN,NaN,NaN
Hydraulics,Auxiliary,Standard,Auxiliary,Standard,Standard
Pushblock,NaN,NaN,NaN,NaN,NaN
Ripper,NaN,NaN,NaN,NaN,NaN
Scarifier,NaN,NaN,NaN,NaN,NaN
Tip_Control,NaN,NaN,NaN,NaN,NaN
Tire_Size,NaN,NaN,NaN,NaN,NaN
Coupler,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Coupler_System,NaN,NaN,NaN,NaN,NaN
Grouser_Tracks,NaN,NaN,NaN,NaN,NaN
Hydraulics_Flow,NaN,NaN,NaN,NaN,NaN
Track_Type,Steel,Steel,Steel,Steel,Steel
Undercarriage_Pad_Width,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Stick_Length,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Thumb,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Pattern_Changer,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Grouser_Type,Double,Double,Double,Double,Double
Backhoe_Mounting,NaN,NaN,NaN,NaN,NaN
Blade_Type,NaN,NaN,NaN,NaN,NaN
Travel_Controls,NaN,NaN,NaN,NaN,NaN
Differential_Type,NaN,NaN,NaN,NaN,NaN
Steering_Controls,NaN,NaN,NaN,NaN,NaN

In [170]:
display_all(df_raw.tail().transpose())

,401120,401121,401122,401123,401124
SalesID,6333336,6333337,6333338,6333341,6333342
SalePrice,10500,11000,11500,9000,7750
MachineID,1840702,1830472,1887659,1903570,1926965
ModelID,21439,21439,21439,21435,21435
datasource,149,149,149,149,149
auctioneerID,1,1,1,2,2
YearMade,2005,2005,2005,2005,2005
MachineHoursCurrentMeter,NaN,NaN,NaN,NaN,NaN
UsageBand,NaN,NaN,NaN,NaN,NaN
saledate,2011-11-02 00:00:00,2011-11-02 00:00:00,2011-11-02 00:00:00,2011-10-25 00:00:00,2011-10-25 00:00:00
fiModelDesc,35NX2,35NX2,35NX2,30NX,30NX
fiBaseModel,35,35,35,30,30
fiSecondaryDesc,NX,NX,NX,NX,NX
fiModelSeries,2,2,2,NaN,NaN
fiModelDescriptor,NaN,NaN,NaN,NaN,NaN
ProductSize,Mini,Mini,Mini,Mini,Mini
fiProductClassDesc,"Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 3.0 to 4.0 Metric...","Hydraulic Excavator, Track - 2.0 to 3.0 Metric...","Hydraulic Excavator, Track - 2.0 to 3.0 Metric..."
state,Maryland,Maryland,Maryland,Florida,Florida
ProductGroup,TEX,TEX,TEX,TEX,TEX
ProductGroupDesc,Track Excavators,Track Excavators,Track Excavators,Track Excavators,Track Excavators
Drive_System,NaN,NaN,NaN,NaN,NaN
Enclosure,EROPS,EROPS,EROPS,EROPS,EROPS
Forks,NaN,NaN,NaN,NaN,NaN
Pad_Type,NaN,NaN,NaN,NaN,NaN
Ride_Control,NaN,NaN,NaN,NaN,NaN
Stick,NaN,NaN,NaN,NaN,NaN
Transmission,NaN,NaN,NaN,NaN,NaN
Turbocharged,NaN,NaN,NaN,NaN,NaN
Blade_Extension,NaN,NaN,NaN,NaN,NaN
Blade_Width,NaN,NaN,NaN,NaN,NaN
Enclosure_Type,NaN,NaN,NaN,NaN,NaN
Engine_Horsepower,NaN,NaN,NaN,NaN,NaN
Hydraulics,Auxiliary,Standard,Auxiliary,Standard,Standard
Pushblock,NaN,NaN,NaN,NaN,NaN
Ripper,NaN,NaN,NaN,NaN,NaN
Scarifier,NaN,NaN,NaN,NaN,NaN
Tip_Control,NaN,NaN,NaN,NaN,NaN
Tire_Size,NaN,NaN,NaN,NaN,NaN
Coupler,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Coupler_System,NaN,NaN,NaN,NaN,NaN
Grouser_Tracks,NaN,NaN,NaN,NaN,NaN
Hydraulics_Flow,NaN,NaN,NaN,NaN,NaN
Track_Type,Steel,Steel,Steel,Steel,Steel
Undercarriage_Pad_Width,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Stick_Length,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Thumb,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Pattern_Changer,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified
Grouser_Type,Double,Double,Double,Double,Double
Backhoe_Mounting,NaN,NaN,NaN,NaN,NaN
Blade_Type,NaN,NaN,NaN,NaN,NaN
Travel_Controls,NaN,NaN,NaN,NaN,NaN
Differential_Type,NaN,NaN,NaN,NaN,NaN
Steering_Controls,NaN,NaN,NaN,NaN,NaN

In [0]:
df_raw.SalePrice = np.log(df_raw.SalePrice)

In [172]:
df_raw.SalePrice

0         11.097410
1         10.950807
2          9.210340
3         10.558414
4          9.305651
5         10.184900
6          9.952278
7         10.203592
8          9.975808
9         11.082143
10        10.085809
11        10.021271
12        10.491274
13        10.325482
14        10.239960
15         9.852194
16         9.510445
17         9.159047
18         9.433484
19         9.350102
20        10.621327
21        10.448715
22        10.165852
23        11.198215
24        10.404263
25         9.433484
26         9.648595
27        10.878047
28        10.736397
29        11.396392
            ...
401095     9.259131
401096     9.210340
401097     9.047821
401098     9.259131
401099     9.305651
401100     9.259131
401101     9.210340
401102     9.259131
401103     9.433484
401104     9.259131
401105     9.210340
401106     9.259131
401107     9.433484
401108     9.259131
401109     9.259131
401110     9.259131
401111     9.210340
401112     9.259131
401113     9.259131
401114     9.433484
401115     9.210340
401116     9.047821
401117     9.210340
401118     9.159047
401119     9.047821
401120     9.259131
401121     9.305651
401122     9.350102
401123     9.104980
401124     8.955448
Name: SalePrice, Length: 401125, dtype: float64

In [0]:
#Random Forest predict columns of any size.
## Generally does not overfit
##

In [0]:
train_cats(df_raw)
#df_raw
#df_raw.Steering_Controls

#Add a column for age of bulldozer
df_raw['age'] = df_raw['saleYear'] - df_raw['YearMade'] 

train_cats(df_raw)

df_raw.UsageBand.cat.set_categories(['High', 'Medium', 'Low'], ordered=True, inplace=True)
df_raw.UsageBand = df_raw.UsageBand.cat.codes
#Change categories to code and missing values to 0, replace missing numeric values with median, 
#add column to indicate replaced missing values and separate the dependent variable as a separate df
df, y, nas = proc_df(df_raw, 'SalePrice')

#m = RandomForestRegressor(n_jobs = -1)
#m.fit(df_raw.drop('SalePrice',axis =1), df_raw.SalePrice)

In [184]:
df.Steering_Controls
#add_datepart(df_raw, 'saledate')

0         2
1         2
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         2
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        2
24        0
25        0
26        0
27        0
28        0
29        0
         ..
401095    0
401096    0
401097    0
401098    0
401099    0
401100    0
401101    0
401102    0
401103    0
401104    0
401105    0
401106    0
401107    0
401108    0
401109    0
401110    0
401111    0
401112    0
401113    0
401114    0
401115    0
401116    0
401117    0
401118    0
401119    0
401120    0
401121    0
401122    0
401123    0
401124    0
Name: Steering_Controls, Length: 401125, dtype: int8

In [0]:
df_raw.saleYear.head()
#df_raw
def split_vals(a,n): 
    return a[:n].copy(), a[n:].copy()

n_valid = 12000  # same as Kaggle's test set size
n_trn = len(df)-n_valid
raw_train, raw_valid = split_vals(df_raw, n_trn) #for using unprocessed data if needed.
X_train, X_valid = split_vals(df, n_trn)
y_train, y_valid = split_vals(y, n_trn)

In [188]:
X_train.shape, X_valid.shape, y_train.shape, y_valid.shape
m = RandomForestRegressor(n_jobs=-1)
m.fit(X_train, y_train)
print_score(m);

NameError: ignored

In [190]:
def rmse(x,y): 
    return math.sqrt(((x-y)**2).mean())

def print_score(m):
    res = [rmse(m.predict(X_train), y_train), rmse(m.predict(X_valid), y_valid),
                m.score(X_train, y_train), m.score(X_valid, y_valid)]
    if hasattr(m, 'oob_score_'): res.append(m.oob_score_)
    print(res)
    
    
print_score(m);

[0.09067718552238346, 0.24680419676298415, 0.9828157378325741, 0.8912189980418561]

In [193]:
df.head()

,SalesID,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,fiModelDesc,fiBaseModel,...,saleIs_month_end,saleIs_month_start,saleIs_quarter_end,saleIs_quarter_start,saleIs_year_end,saleIs_year_start,saleElapsed,age,auctioneerID_na,MachineHoursCurrentMeter_na
0,1139246,999089,3157,121,3.0,2004,68.0,2,950,296,...,False,False,False,False,False,False,1163635200,2,False,False
1,1139248,117657,77,121,3.0,1996,4640.0,2,1725,527,...,False,False,False,False,False,False,1080259200,8,False,False
2,1139249,434808,7009,121,3.0,2001,2838.0,0,331,110,...,False,False,False,False,False,False,1077753600,3,False,False
3,1139251,1026470,332,121,3.0,2001,3486.0,0,3674,1375,...,False,False,False,False,False,False,1305763200,10,False,False
4,1139253,1057373,17311,121,3.0,2007,722.0,1,4208,1529,...,False,False,False,False,False,False,1248307200,2,False,False

In [197]:
m = RandomForestRegressor(n_jobs=-1)
m.fit(df, y)
m.score(df,y)
#train_cats(df_raw)
#df_raw

0.9829785155714666

In [105]:
df_raw.UsageBand.cat.categories

AttributeError: ignored

In [106]:
df_raw.UsageBand.cat.set_categories(['High', 'Medium', 'Low'], ordered=True, inplace=True)

AttributeError: ignored

In [107]:
df_raw.UsageBand = df_raw.UsageBand.cat.codes

AttributeError: ignored

In [108]:
display_all(df_raw.isnull().sum().sort_index()/len(df_raw))

Backhoe_Mounting            0.803872
Blade_Extension             0.937129
Blade_Type                  0.800977
Blade_Width                 0.937129
Coupler                     0.466620
Coupler_System              0.891660
Differential_Type           0.826959
Drive_System                0.739829
Enclosure                   0.000810
Enclosure_Type              0.937129
Engine_Horsepower           0.937129
Forks                       0.521154
Grouser_Tracks              0.891899
Grouser_Type                0.752813
Hydraulics                  0.200823
Hydraulics_Flow             0.891899
MachineHoursCurrentMeter    0.644089
MachineID                   0.000000
ModelID                     0.000000
Pad_Type                    0.802720
Pattern_Changer             0.752651
ProductGroup                0.000000
ProductGroupDesc            0.000000
ProductSize                 0.525460
Pushblock                   0.937129
Ride_Control                0.629527
Ripper                      0.740388
SalePrice                   0.000000
SalesID                     0.000000
Scarifier                   0.937102
Steering_Controls           0.827064
Stick                       0.802720
Stick_Length                0.752651
Thumb                       0.752476
Tip_Control                 0.937129
Tire_Size                   0.763869
Track_Type                  0.752813
Transmission                0.543210
Travel_Controls             0.800975
Turbocharged                0.802720
Undercarriage_Pad_Width     0.751020
UsageBand                   0.000000
YearMade                    0.000000
auctioneerID                0.050199
datasource                  0.000000
fiBaseModel                 0.000000
fiModelDesc                 0.000000
fiModelDescriptor           0.820707
fiModelSeries               0.858129
fiProductClassDesc          0.000000
fiSecondaryDesc             0.342016
saleDay                     0.000000
saleDayofweek               0.000000
saleDayofyear               0.000000
saleElapsed                 0.000000
saleIs_month_end            0.000000
saleIs_month_start          0.000000
saleIs_quarter_end          0.000000
saleIs_quarter_start        0.000000
saleIs_year_end             0.000000
saleIs_year_start           0.000000
saleMonth                   0.000000
saleWeek                    0.000000
saleYear                    0.000000
state                       0.000000
dtype: float64

In [0]:
os.makedirs('tmp', exist_ok=True)
df_raw.to_feather('tmp/bulldozers-raw')

In [65]:
df_raw = pd.read_feather('tmp/bulldozers-raw')

/usr/local/lib/python3.6/dist-packages/pandas/io/feather_format.py:112: FutureWarning: `nthreads` argument is deprecated, pass `use_threads` instead
  return feather.read_dataframe(path, nthreads=nthreads)

In [0]:
df,y,nas = proc_df(df_raw)

In [110]:
df.saleIs_month_end, y, nas

(0         False
 1         False
 2         False
 3         False
 4         False
 5         False
 6         False
 7         False
 8         False
 9         False
 10        False
 11        False
 12        False
 13        False
 14        False
 15        False
 16        False
 17        False
 18        False
 19        False
 20        False
 21        False
 22        False
 23        False
 24        False
 25        False
 26        False
 27        False
 28        False
 29        False
           ...
 401095    False
 401096    False
 401097    False
 401098    False
 401099    False
 401100    False
 401101    False
 401102    False
 401103    False
 401104    False
 401105    False
 401106    False
 401107    False
 401108    False
 401109    False
 401110    False
 401111    False
 401112    False
 401113    False
 401114    False
 401115    False
 401116    False
 401117    False
 401118    False
 401119    False
 401120    False
 401121    False
 401122    False
 401123    False
 401124    False
 Name: saleIs_month_end, Length: 401125, dtype: bool,
 None,
 {'MachineHoursCurrentMeter': 0.0, 'auctioneerID': 2.0})

In [111]:
from sklearn import utils
print(utils.multiclass.type_of_target(y))
print(utils.multiclass.type_of_target(y.astype('int')))

ValueError: ignored

In [0]:
m = RandomForestClassifier(n_jobs=-1)

In [113]:
m.fit(df_raw.drop('SalePrice', axis=1), df_raw.SalePrice)

ValueError: ignored

In [86]:
print(utils.multiclass.type_of_target(df))
print(utils.multiclass.type_of_target(df.astype('int')))
m.fit(df,y)

unknown
multiclass-multioutput

ValueError: ignored

In [87]:
m.score(df,y)

NotFittedError: ignored

In [0]:
df.

Index(['SalesID', 'MachineID', 'ModelID', 'datasource', 'auctioneerID',
       'YearMade', 'MachineHoursCurrentMeter', 'UsageBand', 'fiModelDesc',
       'fiBaseModel', 'fiSecondaryDesc', 'fiModelSeries', 'fiModelDescriptor',
       'ProductSize', 'fiProductClassDesc', 'state', 'ProductGroup',
       'ProductGroupDesc', 'Drive_System', 'Enclosure', 'Forks', 'Pad_Type',
       'Ride_Control', 'Stick', 'Transmission', 'Turbocharged',
       'Blade_Extension', 'Blade_Width', 'Enclosure_Type', 'Engine_Horsepower',
       'Hydraulics', 'Pushblock', 'Ripper', 'Scarifier', 'Tip_Control',
       'Tire_Size', 'Coupler', 'Coupler_System', 'Grouser_Tracks',
       'Hydraulics_Flow', 'Track_Type', 'Undercarriage_Pad_Width',
       'Stick_Length', 'Thumb', 'Pattern_Changer', 'Grouser_Type',
       'Backhoe_Mounting', 'Blade_Type', 'Travel_Controls',
       'Differential_Type', 'Steering_Controls', 'saleYear', 'saleMonth',
       'saleWeek', 'saleDay', 'saleDayofweek', 'saleDayofyear',
       'saleIs_month_end', 'saleIs_month_start', 'saleIs_quarter_end',
       'saleIs_quarter_start', 'saleIs_year_end', 'saleIs_year_start',
       'saleElapsed', 'auctioneerID_na', 'MachineHoursCurrentMeter_na'],
      dtype='object')